// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -package dbhandler -destination ./mock_dbhandler.go -source main.go -build_flags=-mod=mod
//

// Package dbhandler is a generated GoMock package.
package dbhandler

import (
	context "context"
	streaming "monorepo/bin-transcribe-manager/models/streaming"
	transcribe "monorepo/bin-transcribe-manager/models/transcribe"
	transcript "monorepo/bin-transcribe-manager/models/transcript"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDBHandler is a mock of DBHandler interface.
type MockDBHandler struct {
	ctrl     *gomock.Controller
	recorder *MockDBHandlerMockRecorder
	isgomock struct{}
}

// MockDBHandlerMockRecorder is the mock recorder for MockDBHandler.
type MockDBHandlerMockRecorder struct {
	mock *MockDBHandler
}

// NewMockDBHandler creates a new mock instance.
func NewMockDBHandler(ctrl *gomock.Controller) *MockDBHandler {
	mock := &MockDBHandler{ctrl: ctrl}
	mock.recorder = &MockDBHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBHandler) EXPECT() *MockDBHandlerMockRecorder {
	return m.recorder
}

// StreamingCreate mocks base method.
func (m *MockDBHandler) StreamingCreate(ctx context.Context, s *streaming.Streaming) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamingCreate", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamingCreate indicates an expected call of StreamingCreate.
func (mr *MockDBHandlerMockRecorder) StreamingCreate(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamingCreate", reflect.TypeOf((*MockDBHandler)(nil).StreamingCreate), ctx, s)
}

// StreamingGet mocks base method.
func (m *MockDBHandler) StreamingGet(ctx context.Context, id uuid.UUID) (*streaming.Streaming, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamingGet", ctx, id)
	ret0, _ := ret[0].(*streaming.Streaming)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamingGet indicates an expected call of StreamingGet.
func (mr *MockDBHandlerMockRecorder) StreamingGet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamingGet", reflect.TypeOf((*MockDBHandler)(nil).StreamingGet), ctx, id)
}

// TranscribeCreate mocks base method.
func (m *MockDBHandler) TranscribeCreate(ctx context.Context, t *transcribe.Transcribe) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranscribeCreate", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// TranscribeCreate indicates an expected call of TranscribeCreate.
func (mr *MockDBHandlerMockRecorder) TranscribeCreate(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranscribeCreate", reflect.TypeOf((*MockDBHandler)(nil).TranscribeCreate), ctx, t)
}

// TranscribeDelete mocks base method.
func (m *MockDBHandler) TranscribeDelete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranscribeDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TranscribeDelete indicates an expected call of TranscribeDelete.
func (mr *MockDBHandlerMockRecorder) TranscribeDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranscribeDelete", reflect.TypeOf((*MockDBHandler)(nil).TranscribeDelete), ctx, id)
}

// TranscribeGet mocks base method.
func (m *MockDBHandler) TranscribeGet(ctx context.Context, id uuid.UUID) (*transcribe.Transcribe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranscribeGet", ctx, id)
	ret0, _ := ret[0].(*transcribe.Transcribe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TranscribeGet indicates an expected call of TranscribeGet.
func (mr *MockDBHandlerMockRecorder) TranscribeGet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranscribeGet", reflect.TypeOf((*MockDBHandler)(nil).TranscribeGet), ctx, id)
}

// TranscribeGetByReferenceIDAndLanguage mocks base method.
func (m *MockDBHandler) TranscribeGetByReferenceIDAndLanguage(ctx context.Context, referenceID uuid.UUID, language string) (*transcribe.Transcribe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranscribeGetByReferenceIDAndLanguage", ctx, referenceID, language)
	ret0, _ := ret[0].(*transcribe.Transcribe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TranscribeGetByReferenceIDAndLanguage indicates an expected call of TranscribeGetByReferenceIDAndLanguage.
func (mr *MockDBHandlerMockRecorder) TranscribeGetByReferenceIDAndLanguage(ctx, referenceID, language any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranscribeGetByReferenceIDAndLanguage", reflect.TypeOf((*MockDBHandler)(nil).TranscribeGetByReferenceIDAndLanguage), ctx, referenceID, language)
}

// TranscribeList mocks base method.
func (m *MockDBHandler) TranscribeList(ctx context.Context, size uint64, token string, filters map[transcribe.Field]any) ([]*transcribe.Transcribe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranscribeList", ctx, size, token, filters)
	ret0, _ := ret[0].([]*transcribe.Transcribe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TranscribeList indicates an expected call of TranscribeList.
func (mr *MockDBHandlerMockRecorder) TranscribeList(ctx, size, token, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranscribeList", reflect.TypeOf((*MockDBHandler)(nil).TranscribeList), ctx, size, token, filters)
}

// TranscribeUpdate mocks base method.
func (m *MockDBHandler) TranscribeUpdate(ctx context.Context, id uuid.UUID, fields map[transcribe.Field]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranscribeUpdate", ctx, id, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// TranscribeUpdate indicates an expected call of TranscribeUpdate.
func (mr *MockDBHandlerMockRecorder) TranscribeUpdate(ctx, id, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranscribeUpdate", reflect.TypeOf((*MockDBHandler)(nil).TranscribeUpdate), ctx, id, fields)
}

// TranscriptCreate mocks base method.
func (m *MockDBHandler) TranscriptCreate(ctx context.Context, t *transcript.Transcript) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranscriptCreate", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// TranscriptCreate indicates an expected call of TranscriptCreate.
func (mr *MockDBHandlerMockRecorder) TranscriptCreate(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranscriptCreate", reflect.TypeOf((*MockDBHandler)(nil).TranscriptCreate), ctx, t)
}

// TranscriptDelete mocks base method.
func (m *MockDBHandler) TranscriptDelete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranscriptDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TranscriptDelete indicates an expected call of TranscriptDelete.
func (mr *MockDBHandlerMockRecorder) TranscriptDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranscriptDelete", reflect.TypeOf((*MockDBHandler)(nil).TranscriptDelete), ctx, id)
}

// TranscriptGet mocks base method.
func (m *MockDBHandler) TranscriptGet(ctx context.Context, id uuid.UUID) (*transcript.Transcript, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranscriptGet", ctx, id)
	ret0, _ := ret[0].(*transcript.Transcript)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TranscriptGet indicates an expected call of TranscriptGet.
func (mr *MockDBHandlerMockRecorder) TranscriptGet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranscriptGet", reflect.TypeOf((*MockDBHandler)(nil).TranscriptGet), ctx, id)
}

// TranscriptList mocks base method.
func (m *MockDBHandler) TranscriptList(ctx context.Context, size uint64, token string, filters map[transcript.Field]any) ([]*transcript.Transcript, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranscriptList", ctx, size, token, filters)
	ret0, _ := ret[0].([]*transcript.Transcript)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TranscriptList indicates an expected call of TranscriptList.
func (mr *MockDBHandlerMockRecorder) TranscriptList(ctx, size, token, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranscriptList", reflect.TypeOf((*MockDBHandler)(nil).TranscriptList), ctx, size, token, filters)
}

// TranscriptUpdate mocks base method.
func (m *MockDBHandler) TranscriptUpdate(ctx context.Context, id uuid.UUID, fields map[transcript.Field]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranscriptUpdate", ctx, id, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// TranscriptUpdate indicates an expected call of TranscriptUpdate.
func (mr *MockDBHandlerMockRecorder) TranscriptUpdate(ctx, id, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranscriptUpdate", reflect.TypeOf((*MockDBHandler)(nil).TranscriptUpdate), ctx, id, fields)
}
