// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -package participanthandler -destination ./mock_main.go -source main.go -build_flags=-mod=mod
//

// Package participanthandler is a generated GoMock package.
package participanthandler

import (
	context "context"
	chat "monorepo/bin-talk-manager/models/chat"
	participant "monorepo/bin-talk-manager/models/participant"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockParticipantHandler is a mock of ParticipantHandler interface.
type MockParticipantHandler struct {
	ctrl     *gomock.Controller
	recorder *MockParticipantHandlerMockRecorder
	isgomock struct{}
}

// MockParticipantHandlerMockRecorder is the mock recorder for MockParticipantHandler.
type MockParticipantHandlerMockRecorder struct {
	mock *MockParticipantHandler
}

// NewMockParticipantHandler creates a new mock instance.
func NewMockParticipantHandler(ctrl *gomock.Controller) *MockParticipantHandler {
	mock := &MockParticipantHandler{ctrl: ctrl}
	mock.recorder = &MockParticipantHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParticipantHandler) EXPECT() *MockParticipantHandlerMockRecorder {
	return m.recorder
}

// ParticipantAdd mocks base method.
func (m *MockParticipantHandler) ParticipantAdd(ctx context.Context, chatID, ownerID uuid.UUID, ownerType string) (*participant.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParticipantAdd", ctx, chatID, ownerID, ownerType)
	ret0, _ := ret[0].(*participant.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParticipantAdd indicates an expected call of ParticipantAdd.
func (mr *MockParticipantHandlerMockRecorder) ParticipantAdd(ctx, chatID, ownerID, ownerType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParticipantAdd", reflect.TypeOf((*MockParticipantHandler)(nil).ParticipantAdd), ctx, chatID, ownerID, ownerType)
}

// ParticipantList mocks base method.
func (m *MockParticipantHandler) ParticipantList(ctx context.Context, customerID, chatID uuid.UUID) ([]*participant.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParticipantList", ctx, customerID, chatID)
	ret0, _ := ret[0].([]*participant.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParticipantList indicates an expected call of ParticipantList.
func (mr *MockParticipantHandlerMockRecorder) ParticipantList(ctx, customerID, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParticipantList", reflect.TypeOf((*MockParticipantHandler)(nil).ParticipantList), ctx, customerID, chatID)
}

// ParticipantListWithFilters mocks base method.
func (m *MockParticipantHandler) ParticipantListWithFilters(ctx context.Context, filters map[participant.Field]any, token string, size uint64) ([]*participant.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParticipantListWithFilters", ctx, filters, token, size)
	ret0, _ := ret[0].([]*participant.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParticipantListWithFilters indicates an expected call of ParticipantListWithFilters.
func (mr *MockParticipantHandlerMockRecorder) ParticipantListWithFilters(ctx, filters, token, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParticipantListWithFilters", reflect.TypeOf((*MockParticipantHandler)(nil).ParticipantListWithFilters), ctx, filters, token, size)
}

// ParticipantRemove mocks base method.
func (m *MockParticipantHandler) ParticipantRemove(ctx context.Context, customerID, participantID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParticipantRemove", ctx, customerID, participantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ParticipantRemove indicates an expected call of ParticipantRemove.
func (mr *MockParticipantHandlerMockRecorder) ParticipantRemove(ctx, customerID, participantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParticipantRemove", reflect.TypeOf((*MockParticipantHandler)(nil).ParticipantRemove), ctx, customerID, participantID)
}

// MockDBHandler is a mock of DBHandler interface.
type MockDBHandler struct {
	ctrl     *gomock.Controller
	recorder *MockDBHandlerMockRecorder
	isgomock struct{}
}

// MockDBHandlerMockRecorder is the mock recorder for MockDBHandler.
type MockDBHandlerMockRecorder struct {
	mock *MockDBHandler
}

// NewMockDBHandler creates a new mock instance.
func NewMockDBHandler(ctrl *gomock.Controller) *MockDBHandler {
	mock := &MockDBHandler{ctrl: ctrl}
	mock.recorder = &MockDBHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBHandler) EXPECT() *MockDBHandlerMockRecorder {
	return m.recorder
}

// ChatGet mocks base method.
func (m *MockDBHandler) ChatGet(ctx context.Context, id uuid.UUID) (*chat.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatGet", ctx, id)
	ret0, _ := ret[0].(*chat.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatGet indicates an expected call of ChatGet.
func (mr *MockDBHandlerMockRecorder) ChatGet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatGet", reflect.TypeOf((*MockDBHandler)(nil).ChatGet), ctx, id)
}

// ChatMemberCountDecrement mocks base method.
func (m *MockDBHandler) ChatMemberCountDecrement(ctx context.Context, chatID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatMemberCountDecrement", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChatMemberCountDecrement indicates an expected call of ChatMemberCountDecrement.
func (mr *MockDBHandlerMockRecorder) ChatMemberCountDecrement(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatMemberCountDecrement", reflect.TypeOf((*MockDBHandler)(nil).ChatMemberCountDecrement), ctx, chatID)
}

// ChatMemberCountIncrement mocks base method.
func (m *MockDBHandler) ChatMemberCountIncrement(ctx context.Context, chatID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatMemberCountIncrement", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChatMemberCountIncrement indicates an expected call of ChatMemberCountIncrement.
func (mr *MockDBHandlerMockRecorder) ChatMemberCountIncrement(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatMemberCountIncrement", reflect.TypeOf((*MockDBHandler)(nil).ChatMemberCountIncrement), ctx, chatID)
}

// ParticipantCreate mocks base method.
func (m *MockDBHandler) ParticipantCreate(ctx context.Context, p *participant.Participant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParticipantCreate", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// ParticipantCreate indicates an expected call of ParticipantCreate.
func (mr *MockDBHandlerMockRecorder) ParticipantCreate(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParticipantCreate", reflect.TypeOf((*MockDBHandler)(nil).ParticipantCreate), ctx, p)
}

// ParticipantDelete mocks base method.
func (m *MockDBHandler) ParticipantDelete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParticipantDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ParticipantDelete indicates an expected call of ParticipantDelete.
func (mr *MockDBHandlerMockRecorder) ParticipantDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParticipantDelete", reflect.TypeOf((*MockDBHandler)(nil).ParticipantDelete), ctx, id)
}

// ParticipantGet mocks base method.
func (m *MockDBHandler) ParticipantGet(ctx context.Context, id uuid.UUID) (*participant.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParticipantGet", ctx, id)
	ret0, _ := ret[0].(*participant.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParticipantGet indicates an expected call of ParticipantGet.
func (mr *MockDBHandlerMockRecorder) ParticipantGet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParticipantGet", reflect.TypeOf((*MockDBHandler)(nil).ParticipantGet), ctx, id)
}

// ParticipantList mocks base method.
func (m *MockDBHandler) ParticipantList(ctx context.Context, filters map[participant.Field]any) ([]*participant.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParticipantList", ctx, filters)
	ret0, _ := ret[0].([]*participant.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParticipantList indicates an expected call of ParticipantList.
func (mr *MockDBHandlerMockRecorder) ParticipantList(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParticipantList", reflect.TypeOf((*MockDBHandler)(nil).ParticipantList), ctx, filters)
}

// MockSockHandler is a mock of SockHandler interface.
type MockSockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockSockHandlerMockRecorder
	isgomock struct{}
}

// MockSockHandlerMockRecorder is the mock recorder for MockSockHandler.
type MockSockHandlerMockRecorder struct {
	mock *MockSockHandler
}

// NewMockSockHandler creates a new mock instance.
func NewMockSockHandler(ctrl *gomock.Controller) *MockSockHandler {
	mock := &MockSockHandler{ctrl: ctrl}
	mock.recorder = &MockSockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSockHandler) EXPECT() *MockSockHandlerMockRecorder {
	return m.recorder
}
