// Code generated by MockGen. DO NOT EDIT.
// Source: main.go

// Package storagehandler is a generated GoMock package.
package storagehandler

import (
	context "context"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	gomock "github.com/golang/mock/gomock"
	bucketfile "gitlab.com/voipbin/bin-manager/storage-manager.git/models/bucketfile"
)

// MockStorageHandler is a mock of StorageHandler interface.
type MockStorageHandler struct {
	ctrl     *gomock.Controller
	recorder *MockStorageHandlerMockRecorder
}

// MockStorageHandlerMockRecorder is the mock recorder for MockStorageHandler.
type MockStorageHandlerMockRecorder struct {
	mock *MockStorageHandler
}

// NewMockStorageHandler creates a new mock instance.
func NewMockStorageHandler(ctrl *gomock.Controller) *MockStorageHandler {
	mock := &MockStorageHandler{ctrl: ctrl}
	mock.recorder = &MockStorageHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageHandler) EXPECT() *MockStorageHandlerMockRecorder {
	return m.recorder
}

// GetRecording mocks base method.
func (m *MockStorageHandler) GetRecording(ctx context.Context, id uuid.UUID) (*bucketfile.BucketFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecording", ctx, id)
	ret0, _ := ret[0].(*bucketfile.BucketFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecording indicates an expected call of GetRecording.
func (mr *MockStorageHandlerMockRecorder) GetRecording(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecording", reflect.TypeOf((*MockStorageHandler)(nil).GetRecording), ctx, id)
}
