apiVersion: batch/v1
kind: CronJob
metadata:
  name: number-renew
spec:
  schedule: "0 1 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 3600
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: bin-trigger-sender
            image: voipbin/bin-trigger-sender:latest
            imagePullPolicy: Always
            env:
            - name: RABBITMQ_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: RABBITMQ_ADDRESS
            command:
            - /app/bin/bin-trigger-sender
            - -rabbit_addr
            - $(RABBITMQ_ADDRESS)
            - -queue
            - 'bin-manager.number-manager.request'
            - -uri
            - '/v1/numbers/renew'
            - -method
            - 'POST'
            - -data_type
            - 'application/json'
            - -data
            - '{"days":28}'
            - -timeout
            - '3000'
            - -delay
            - '0'
