apiVersion: apps/v1
kind: Deployment
metadata:
  name: number-manager
  labels:
    app: number-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: number-manager
  template:
    metadata:
      labels:
        app: number-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "2112"
    spec:
      containers:
        - name: number-manager
          image: number-manager-image
          command:
            - './number-manager'
          env:
            - name: DATABASE_DSN
              value: ${DATABASE_DSN}
            - name: PROMETHEUS_ENDPOINT
              value: "/metrics"
            - name: PROMETHEUS_LISTEN_ADDRESS
              value: ":2112"
            - name: RABBITMQ_ADDRESS
              value: ${RABBITMQ_ADDRESS}
            - name: REDIS_ADDRESS
              value: ${REDIS_ADDRESS}
            - name: REDIS_PASSWORD
              value: ${REDIS_PASSWORD}
            - name: REDIS_DATABASE
              value: "1"
            - name: TWILIO_SID
              value: ${TWILIO_SID}
            - name: TWILIO_TOKEN
              value: ${TWILIO_TOKEN}
            - name: TELNYX_CONNECTION_ID
              value: ${TELNYX_CONNECTION_ID}
            - name: TELNYX_PROFILE_ID
              value: ${TELNYX_PROFILE_ID}
            - name: TELNYX_TOKEN
              value: ${TELNYX_TOKEN}
          ports:
            - name: metrics
              protocol: "TCP"
              containerPort: 2112
          resources:
            limits:
              cpu: "30m"
              memory: "20M"
