apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcribe-manager
  labels:
    app: transcribe-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transcribe-manager
  template:
    metadata:
      labels:
        app: transcribe-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "2112"
    spec:
      volumes:
        - name: google-application-credentials
          secret:
            secretName: voipbin
            items:
              - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
                path: service-account.json
      containers:
        - name: transcribe-manager
          image: transcribe-manager-image
          command:
            - './transcribe-manager'
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: DATABASE_DSN_BIN
            - name: PROMETHEUS_ENDPOINT
              value: "/metrics"
            - name: PROMETHEUS_LISTEN_ADDRESS
              value: ":2112"
            - name: RABBITMQ_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: RABBITMQ_ADDRESS
            - name: REDIS_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: REDIS_ADDRESS
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: REDIS_PASSWORD
            - name: REDIS_DATABASE
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: REDIS_DATABASE
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: AWS_SECRET_KEY
            - name: STREAMING_LISTEN_PORT
              value: "8080"
            - name: STT_PROVIDER_PRIORITY
              value: "GCP,AWS"
            - name: CLICKHOUSE_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: CLICKHOUSE_ADDRESS
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/google/service-account.json"
          volumeMounts:
            - name: google-application-credentials
              mountPath: /var/secrets/google
              readOnly: true
          resources:
            requests:
              cpu: "6m"
              memory: "8M"
            limits:
              cpu: "60m"
              memory: "80M"
          ports:
            - name: metrics
              protocol: "TCP"
              containerPort: 2112
            - name: audiosocket
              protocol: "TCP"
              containerPort: 8080
