apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcribe-manager
  labels:
    app: transcribe-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transcribe-manager
  template:
    metadata:
      labels:
        app: transcribe-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "2112"
    spec:
      containers:
        - name: transcribe-manager
          image: transcribe-manager-image
          command:
            - './transcribe-manager'
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DATABASE_DSN
              value: ${DATABASE_DSN}
            - name: PROMETHEUS_ENDPOINT
              value: "/metrics"
            - name: PROMETHEUS_LISTEN_ADDRESS
              value: ":2112"
            - name: RABBITMQ_ADDRESS
              value: ${RABBITMQ_ADDRESS}
            - name: REDIS_ADDRESS
              value: ${REDIS_ADDRESS}
            - name: REDIS_PASSWORD
              value: ${REDIS_PASSWORD}
            - name: REDIS_DATABASE
              value: "1"
            - name: GCP_CREDENTIAL_BASE64
              value: ${GCP_SERVICE_ACCOUNT_BASE64}
          resources:
            limits:
              cpu: "60m"
              memory: "80M"
          ports:
            - name: metrics
              protocol: "TCP"
              containerPort: 2112
            - name: audiosocket
              protocol: "TCP"
              containerPort: 8080
