// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -package stackmaphandler -destination ./mock_main.go -source main.go -build_flags=-mod=mod
//

// Package stackmaphandler is a generated GoMock package.
package stackmaphandler

import (
	action "monorepo/bin-flow-manager/models/action"
	stack "monorepo/bin-flow-manager/models/stack"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStackmapHandler is a mock of StackmapHandler interface.
type MockStackmapHandler struct {
	ctrl     *gomock.Controller
	recorder *MockStackmapHandlerMockRecorder
	isgomock struct{}
}

// MockStackmapHandlerMockRecorder is the mock recorder for MockStackmapHandler.
type MockStackmapHandlerMockRecorder struct {
	mock *MockStackmapHandler
}

// NewMockStackmapHandler creates a new mock instance.
func NewMockStackmapHandler(ctrl *gomock.Controller) *MockStackmapHandler {
	mock := &MockStackmapHandler{ctrl: ctrl}
	mock.recorder = &MockStackmapHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStackmapHandler) EXPECT() *MockStackmapHandlerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStackmapHandler) Create(actions []action.Action) map[uuid.UUID]*stack.Stack {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", actions)
	ret0, _ := ret[0].(map[uuid.UUID]*stack.Stack)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStackmapHandlerMockRecorder) Create(actions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStackmapHandler)(nil).Create), actions)
}

// GetAction mocks base method.
func (m *MockStackmapHandler) GetAction(stackMap map[uuid.UUID]*stack.Stack, currentStackID, targetActionID uuid.UUID, releaseStack bool) (uuid.UUID, *action.Action, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAction", stackMap, currentStackID, targetActionID, releaseStack)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(*action.Action)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAction indicates an expected call of GetAction.
func (mr *MockStackmapHandlerMockRecorder) GetAction(stackMap, currentStackID, targetActionID, releaseStack any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAction", reflect.TypeOf((*MockStackmapHandler)(nil).GetAction), stackMap, currentStackID, targetActionID, releaseStack)
}

// GetNextAction mocks base method.
func (m *MockStackmapHandler) GetNextAction(stackMap map[uuid.UUID]*stack.Stack, currentStackID uuid.UUID, currentAction *action.Action, relaseStack bool) (uuid.UUID, *action.Action) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextAction", stackMap, currentStackID, currentAction, relaseStack)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(*action.Action)
	return ret0, ret1
}

// GetNextAction indicates an expected call of GetNextAction.
func (mr *MockStackmapHandlerMockRecorder) GetNextAction(stackMap, currentStackID, currentAction, relaseStack any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextAction", reflect.TypeOf((*MockStackmapHandler)(nil).GetNextAction), stackMap, currentStackID, currentAction, relaseStack)
}

// PopStack mocks base method.
func (m *MockStackmapHandler) PopStack(stackMap map[uuid.UUID]*stack.Stack, stackID uuid.UUID) (*stack.Stack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PopStack", stackMap, stackID)
	ret0, _ := ret[0].(*stack.Stack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PopStack indicates an expected call of PopStack.
func (mr *MockStackmapHandlerMockRecorder) PopStack(stackMap, stackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PopStack", reflect.TypeOf((*MockStackmapHandler)(nil).PopStack), stackMap, stackID)
}

// PushStackByActions mocks base method.
func (m *MockStackmapHandler) PushStackByActions(stackMap map[uuid.UUID]*stack.Stack, stackID uuid.UUID, actions []action.Action, currentStackID, currentActionID uuid.UUID) (*stack.Stack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushStackByActions", stackMap, stackID, actions, currentStackID, currentActionID)
	ret0, _ := ret[0].(*stack.Stack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PushStackByActions indicates an expected call of PushStackByActions.
func (mr *MockStackmapHandlerMockRecorder) PushStackByActions(stackMap, stackID, actions, currentStackID, currentActionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushStackByActions", reflect.TypeOf((*MockStackmapHandler)(nil).PushStackByActions), stackMap, stackID, actions, currentStackID, currentActionID)
}

// SearchAction mocks base method.
func (m *MockStackmapHandler) SearchAction(stackMap map[uuid.UUID]*stack.Stack, stackID, actionID uuid.UUID) (uuid.UUID, *action.Action, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAction", stackMap, stackID, actionID)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(*action.Action)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchAction indicates an expected call of SearchAction.
func (mr *MockStackmapHandlerMockRecorder) SearchAction(stackMap, stackID, actionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAction", reflect.TypeOf((*MockStackmapHandler)(nil).SearchAction), stackMap, stackID, actionID)
}
