// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -package extensionhandler -destination ./mock_main.go -source main.go -build_flags=-mod=mod
//

// Package extensionhandler is a generated GoMock package.
package extensionhandler

import (
	context "context"
	customer "monorepo/bin-customer-manager/models/customer"
	extension "monorepo/bin-registrar-manager/models/extension"
	extensiondirect "monorepo/bin-registrar-manager/models/extensiondirect"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockExtensionHandler is a mock of ExtensionHandler interface.
type MockExtensionHandler struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionHandlerMockRecorder
	isgomock struct{}
}

// MockExtensionHandlerMockRecorder is the mock recorder for MockExtensionHandler.
type MockExtensionHandlerMockRecorder struct {
	mock *MockExtensionHandler
}

// NewMockExtensionHandler creates a new mock instance.
func NewMockExtensionHandler(ctrl *gomock.Controller) *MockExtensionHandler {
	mock := &MockExtensionHandler{ctrl: ctrl}
	mock.recorder = &MockExtensionHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionHandler) EXPECT() *MockExtensionHandlerMockRecorder {
	return m.recorder
}

// CountByCustomerID mocks base method.
func (m *MockExtensionHandler) CountByCustomerID(ctx context.Context, customerID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByCustomerID", ctx, customerID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByCustomerID indicates an expected call of CountByCustomerID.
func (mr *MockExtensionHandlerMockRecorder) CountByCustomerID(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByCustomerID", reflect.TypeOf((*MockExtensionHandler)(nil).CountByCustomerID), ctx, customerID)
}

// Create mocks base method.
func (m *MockExtensionHandler) Create(ctx context.Context, customerID uuid.UUID, name, detail, ext, password string) (*extension.Extension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, customerID, name, detail, ext, password)
	ret0, _ := ret[0].(*extension.Extension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockExtensionHandlerMockRecorder) Create(ctx, customerID, name, detail, ext, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExtensionHandler)(nil).Create), ctx, customerID, name, detail, ext, password)
}

// Delete mocks base method.
func (m *MockExtensionHandler) Delete(ctx context.Context, id uuid.UUID) (*extension.Extension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*extension.Extension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockExtensionHandlerMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExtensionHandler)(nil).Delete), ctx, id)
}

// DirectDisable mocks base method.
func (m *MockExtensionHandler) DirectDisable(ctx context.Context, extensionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DirectDisable", ctx, extensionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DirectDisable indicates an expected call of DirectDisable.
func (mr *MockExtensionHandlerMockRecorder) DirectDisable(ctx, extensionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DirectDisable", reflect.TypeOf((*MockExtensionHandler)(nil).DirectDisable), ctx, extensionID)
}

// DirectEnable mocks base method.
func (m *MockExtensionHandler) DirectEnable(ctx context.Context, extensionID uuid.UUID) (*extensiondirect.ExtensionDirect, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DirectEnable", ctx, extensionID)
	ret0, _ := ret[0].(*extensiondirect.ExtensionDirect)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DirectEnable indicates an expected call of DirectEnable.
func (mr *MockExtensionHandlerMockRecorder) DirectEnable(ctx, extensionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DirectEnable", reflect.TypeOf((*MockExtensionHandler)(nil).DirectEnable), ctx, extensionID)
}

// DirectRegenerate mocks base method.
func (m *MockExtensionHandler) DirectRegenerate(ctx context.Context, extensionID uuid.UUID) (*extensiondirect.ExtensionDirect, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DirectRegenerate", ctx, extensionID)
	ret0, _ := ret[0].(*extensiondirect.ExtensionDirect)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DirectRegenerate indicates an expected call of DirectRegenerate.
func (mr *MockExtensionHandlerMockRecorder) DirectRegenerate(ctx, extensionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DirectRegenerate", reflect.TypeOf((*MockExtensionHandler)(nil).DirectRegenerate), ctx, extensionID)
}

// EventCUCustomerDeleted mocks base method.
func (m *MockExtensionHandler) EventCUCustomerDeleted(ctx context.Context, cu *customer.Customer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventCUCustomerDeleted", ctx, cu)
	ret0, _ := ret[0].(error)
	return ret0
}

// EventCUCustomerDeleted indicates an expected call of EventCUCustomerDeleted.
func (mr *MockExtensionHandlerMockRecorder) EventCUCustomerDeleted(ctx, cu any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventCUCustomerDeleted", reflect.TypeOf((*MockExtensionHandler)(nil).EventCUCustomerDeleted), ctx, cu)
}

// Get mocks base method.
func (m *MockExtensionHandler) Get(ctx context.Context, id uuid.UUID) (*extension.Extension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*extension.Extension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockExtensionHandlerMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockExtensionHandler)(nil).Get), ctx, id)
}

// GetByExtension mocks base method.
func (m *MockExtensionHandler) GetByExtension(ctx context.Context, customerID uuid.UUID, ext string) (*extension.Extension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByExtension", ctx, customerID, ext)
	ret0, _ := ret[0].(*extension.Extension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByExtension indicates an expected call of GetByExtension.
func (mr *MockExtensionHandlerMockRecorder) GetByExtension(ctx, customerID, ext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByExtension", reflect.TypeOf((*MockExtensionHandler)(nil).GetByExtension), ctx, customerID, ext)
}

// GetDirectByHash mocks base method.
func (m *MockExtensionHandler) GetDirectByHash(ctx context.Context, hash string) (*extensiondirect.ExtensionDirect, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDirectByHash", ctx, hash)
	ret0, _ := ret[0].(*extensiondirect.ExtensionDirect)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDirectByHash indicates an expected call of GetDirectByHash.
func (mr *MockExtensionHandlerMockRecorder) GetDirectByHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDirectByHash", reflect.TypeOf((*MockExtensionHandler)(nil).GetDirectByHash), ctx, hash)
}

// List mocks base method.
func (m *MockExtensionHandler) List(ctx context.Context, token string, limit uint64, filters map[extension.Field]any) ([]*extension.Extension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, token, limit, filters)
	ret0, _ := ret[0].([]*extension.Extension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockExtensionHandlerMockRecorder) List(ctx, token, limit, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockExtensionHandler)(nil).List), ctx, token, limit, filters)
}

// Update mocks base method.
func (m *MockExtensionHandler) Update(ctx context.Context, id uuid.UUID, fields map[extension.Field]any) (*extension.Extension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, fields)
	ret0, _ := ret[0].(*extension.Extension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockExtensionHandlerMockRecorder) Update(ctx, id, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExtensionHandler)(nil).Update), ctx, id, fields)
}
