apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-manager
  labels:
    app: message-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: message-manager
  template:
    metadata:
      labels:
        app: message-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "2112"
    spec:
      containers:
        - name: message-manager
          image: message-manager-image
          command:
            - './message-manager'
          env:
            - name: DATABASE_DSN
              value: ${DATABASE_DSN}
            - name: PROMETHEUS_ENDPOINT
              value: "/metrics"
            - name: PROMETHEUS_LISTEN_ADDRESS
              value: ":2112"
            - name: RABBITMQ_ADDRESS
              value: ${RABBITMQ_ADDRESS}
            - name: REDIS_ADDRESS
              value: ${REDIS_ADDRESS}
            - name: REDIS_PASSWORD
              value: ${REDIS_PASSWORD}
            - name: REDIS_DATABASE
              value: "1"
            - name: AUTHTOKEN_MESSAGEBIRD
              value: ${AUTHTOKEN_MESSAGEBIRD}
          ports:
            - name: metrics
              protocol: "TCP"
              containerPort: 2112
          resources:
            limits:
              cpu: "10m"
              memory: "20M"
