apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bin-manager
commonLabels:
  app: bin-manager

resources:
  - namespace.yml
  - deployment.yml
  - service.yml

images:
- name: chat-manager-image
  newName: chat-manager
  newTag: latest
