apiVersion: apps/v1
kind: Deployment
metadata:
  name: call-manager
  labels:
    app: call-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: call-manager
  template:
    metadata:
      labels:
        app: call-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "2112"
    spec:
      containers:
        - name: call-manager
          image: call-manager-image
          command:
            - './call-manager'
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args:
            - '-dbDSN'
            - 'bin-manager:398e02d8-8aaa-11ea-b1f6-9b65a2a4f3a3@tcp(10.126.80.5:3306)/bin_manager'
            - '-prom_endpoint'
            - '/metrics'
            - '-prom_listen_addr'
            - ':2112'
            - '-rabbit_addr'
            - 'amqp://guest:guest@rabbitmq.voipbin.net:5672'
            - '-redis_addr'
            - '10.164.15.220:6379'
            - '-redis_db'
            - '1'
          ports:
            - name: metrics
              protocol: "TCP"
              containerPort: 2112
          resources:
            limits:
              cpu: "30m"
              memory: "30M"
