apiVersion: apps/v1
kind: Deployment
metadata:
  name: call-manager
  labels:
    app: call-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: call-manager
  template:
    metadata:
      labels:
        app: call-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "2112"
    spec:
      containers:
        - name: call-manager
          image: call-manager-image
          command:
            - './call-manager'
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DATABASE_DSN
              value: ${DATABASE_DSN}
            - name: PROMETHEUS_ENDPOINT
              value: "/metrics"
            - name: PROMETHEUS_LISTEN_ADDRESS
              value: ":2112"
            - name: RABBITMQ_ADDRESS
              value: ${RABBITMQ_ADDRESS}
            - name: REDIS_ADDRESS
              value: ${REDIS_ADDRESS}
            - name: REDIS_PASSWORD
              value: ${REDIS_PASSWORD}
            - name: REDIS_DATABASE
              value: "1"
            - name: HOMER_API_ADDRESS
              value: ${HOMER_API_ADDRESS}
            - name: HOMER_AUTH_TOKEN
              value: ${HOMER_AUTH_TOKEN}
            - name: HOMER_WHITELIST
              value: ${HOMER_WHITELIST}
          ports:
            - name: metrics
              protocol: "TCP"
              containerPort: 2112
          resources:
            limits:
              cpu: "30m"
              memory: "30M"
