// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -package dbhandler -destination ./mock_main.go -source main.go -build_flags=-mod=mod
//

// Package dbhandler is a generated GoMock package.
package dbhandler

import (
	context "context"
	number "monorepo/bin-number-manager/models/number"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDBHandler is a mock of DBHandler interface.
type MockDBHandler struct {
	ctrl     *gomock.Controller
	recorder *MockDBHandlerMockRecorder
	isgomock struct{}
}

// MockDBHandlerMockRecorder is the mock recorder for MockDBHandler.
type MockDBHandlerMockRecorder struct {
	mock *MockDBHandler
}

// NewMockDBHandler creates a new mock instance.
func NewMockDBHandler(ctrl *gomock.Controller) *MockDBHandler {
	mock := &MockDBHandler{ctrl: ctrl}
	mock.recorder = &MockDBHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBHandler) EXPECT() *MockDBHandlerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDBHandler) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockDBHandlerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDBHandler)(nil).Close))
}

// NumberCreate mocks base method.
func (m *MockDBHandler) NumberCreate(ctx context.Context, n *number.Number) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumberCreate", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// NumberCreate indicates an expected call of NumberCreate.
func (mr *MockDBHandlerMockRecorder) NumberCreate(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumberCreate", reflect.TypeOf((*MockDBHandler)(nil).NumberCreate), ctx, n)
}

// NumberDelete mocks base method.
func (m *MockDBHandler) NumberDelete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumberDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// NumberDelete indicates an expected call of NumberDelete.
func (mr *MockDBHandlerMockRecorder) NumberDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumberDelete", reflect.TypeOf((*MockDBHandler)(nil).NumberDelete), ctx, id)
}

// NumberGet mocks base method.
func (m *MockDBHandler) NumberGet(ctx context.Context, id uuid.UUID) (*number.Number, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumberGet", ctx, id)
	ret0, _ := ret[0].(*number.Number)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NumberGet indicates an expected call of NumberGet.
func (mr *MockDBHandlerMockRecorder) NumberGet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumberGet", reflect.TypeOf((*MockDBHandler)(nil).NumberGet), ctx, id)
}

// NumberGets mocks base method.
func (m *MockDBHandler) NumberGets(ctx context.Context, size uint64, token string, filters map[number.Field]any) ([]*number.Number, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumberGets", ctx, size, token, filters)
	ret0, _ := ret[0].([]*number.Number)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NumberGets indicates an expected call of NumberGets.
func (mr *MockDBHandlerMockRecorder) NumberGets(ctx, size, token, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumberGets", reflect.TypeOf((*MockDBHandler)(nil).NumberGets), ctx, size, token, filters)
}

// NumberGetsByTMRenew mocks base method.
func (m *MockDBHandler) NumberGetsByTMRenew(ctx context.Context, tmRenew string, size uint64, filters map[number.Field]any) ([]*number.Number, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumberGetsByTMRenew", ctx, tmRenew, size, filters)
	ret0, _ := ret[0].([]*number.Number)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NumberGetsByTMRenew indicates an expected call of NumberGetsByTMRenew.
func (mr *MockDBHandlerMockRecorder) NumberGetsByTMRenew(ctx, tmRenew, size, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumberGetsByTMRenew", reflect.TypeOf((*MockDBHandler)(nil).NumberGetsByTMRenew), ctx, tmRenew, size, filters)
}

// NumberUpdate mocks base method.
func (m *MockDBHandler) NumberUpdate(ctx context.Context, id uuid.UUID, fields map[number.Field]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumberUpdate", ctx, id, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// NumberUpdate indicates an expected call of NumberUpdate.
func (mr *MockDBHandlerMockRecorder) NumberUpdate(ctx, id, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumberUpdate", reflect.TypeOf((*MockDBHandler)(nil).NumberUpdate), ctx, id, fields)
}
