// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -package cachehandler -destination ./mock_main.go -source main.go -build_flags=-mod=mod
//

// Package cachehandler is a generated GoMock package.
package cachehandler

import (
	context "context"
	contact "monorepo/bin-contact-manager/models/contact"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCacheHandler is a mock of CacheHandler interface.
type MockCacheHandler struct {
	ctrl     *gomock.Controller
	recorder *MockCacheHandlerMockRecorder
	isgomock struct{}
}

// MockCacheHandlerMockRecorder is the mock recorder for MockCacheHandler.
type MockCacheHandlerMockRecorder struct {
	mock *MockCacheHandler
}

// NewMockCacheHandler creates a new mock instance.
func NewMockCacheHandler(ctrl *gomock.Controller) *MockCacheHandler {
	mock := &MockCacheHandler{ctrl: ctrl}
	mock.recorder = &MockCacheHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheHandler) EXPECT() *MockCacheHandlerMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockCacheHandler) Connect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockCacheHandlerMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockCacheHandler)(nil).Connect))
}

// ContactDelete mocks base method.
func (m *MockCacheHandler) ContactDelete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContactDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ContactDelete indicates an expected call of ContactDelete.
func (mr *MockCacheHandlerMockRecorder) ContactDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContactDelete", reflect.TypeOf((*MockCacheHandler)(nil).ContactDelete), ctx, id)
}

// ContactGet mocks base method.
func (m *MockCacheHandler) ContactGet(ctx context.Context, id uuid.UUID) (*contact.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContactGet", ctx, id)
	ret0, _ := ret[0].(*contact.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContactGet indicates an expected call of ContactGet.
func (mr *MockCacheHandlerMockRecorder) ContactGet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContactGet", reflect.TypeOf((*MockCacheHandler)(nil).ContactGet), ctx, id)
}

// ContactSet mocks base method.
func (m *MockCacheHandler) ContactSet(ctx context.Context, c *contact.Contact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContactSet", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// ContactSet indicates an expected call of ContactSet.
func (mr *MockCacheHandlerMockRecorder) ContactSet(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContactSet", reflect.TypeOf((*MockCacheHandler)(nil).ContactSet), ctx, c)
}
