// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -package listenhandler -destination ./mock_main.go -source main.go -build_flags=-mod=mod
//

// Package listenhandler is a generated GoMock package.
package listenhandler
