// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -package dbhandler -destination ./mock_main.go -source main.go -build_flags=-mod=mod
//

// Package dbhandler is a generated GoMock package.
package dbhandler

import (
	context "context"
	chat "monorepo/bin-talk-manager/models/chat"
	message "monorepo/bin-talk-manager/models/message"
	participant "monorepo/bin-talk-manager/models/participant"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDBHandler is a mock of DBHandler interface.
type MockDBHandler struct {
	ctrl     *gomock.Controller
	recorder *MockDBHandlerMockRecorder
	isgomock struct{}
}

// MockDBHandlerMockRecorder is the mock recorder for MockDBHandler.
type MockDBHandlerMockRecorder struct {
	mock *MockDBHandler
}

// NewMockDBHandler creates a new mock instance.
func NewMockDBHandler(ctrl *gomock.Controller) *MockDBHandler {
	mock := &MockDBHandler{ctrl: ctrl}
	mock.recorder = &MockDBHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBHandler) EXPECT() *MockDBHandlerMockRecorder {
	return m.recorder
}

// ChatCreate mocks base method.
func (m *MockDBHandler) ChatCreate(ctx context.Context, t *chat.Chat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatCreate", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChatCreate indicates an expected call of ChatCreate.
func (mr *MockDBHandlerMockRecorder) ChatCreate(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatCreate", reflect.TypeOf((*MockDBHandler)(nil).ChatCreate), ctx, t)
}

// ChatDelete mocks base method.
func (m *MockDBHandler) ChatDelete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChatDelete indicates an expected call of ChatDelete.
func (mr *MockDBHandlerMockRecorder) ChatDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatDelete", reflect.TypeOf((*MockDBHandler)(nil).ChatDelete), ctx, id)
}

// ChatGet mocks base method.
func (m *MockDBHandler) ChatGet(ctx context.Context, id uuid.UUID) (*chat.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatGet", ctx, id)
	ret0, _ := ret[0].(*chat.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatGet indicates an expected call of ChatGet.
func (mr *MockDBHandlerMockRecorder) ChatGet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatGet", reflect.TypeOf((*MockDBHandler)(nil).ChatGet), ctx, id)
}

// ChatList mocks base method.
func (m *MockDBHandler) ChatList(ctx context.Context, filters map[chat.Field]any, token string, size uint64) ([]*chat.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatList", ctx, filters, token, size)
	ret0, _ := ret[0].([]*chat.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatList indicates an expected call of ChatList.
func (mr *MockDBHandlerMockRecorder) ChatList(ctx, filters, token, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatList", reflect.TypeOf((*MockDBHandler)(nil).ChatList), ctx, filters, token, size)
}

// ChatUpdate mocks base method.
func (m *MockDBHandler) ChatUpdate(ctx context.Context, id uuid.UUID, fields map[chat.Field]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatUpdate", ctx, id, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChatUpdate indicates an expected call of ChatUpdate.
func (mr *MockDBHandlerMockRecorder) ChatUpdate(ctx, id, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatUpdate", reflect.TypeOf((*MockDBHandler)(nil).ChatUpdate), ctx, id, fields)
}

// FindDirectChatByParticipants mocks base method.
func (m *MockDBHandler) FindDirectChatByParticipants(ctx context.Context, customerID uuid.UUID, ownerType1 string, ownerID1 uuid.UUID, ownerType2 string, ownerID2 uuid.UUID) (*chat.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDirectChatByParticipants", ctx, customerID, ownerType1, ownerID1, ownerType2, ownerID2)
	ret0, _ := ret[0].(*chat.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDirectChatByParticipants indicates an expected call of FindDirectChatByParticipants.
func (mr *MockDBHandlerMockRecorder) FindDirectChatByParticipants(ctx, customerID, ownerType1, ownerID1, ownerType2, ownerID2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDirectChatByParticipants", reflect.TypeOf((*MockDBHandler)(nil).FindDirectChatByParticipants), ctx, customerID, ownerType1, ownerID1, ownerType2, ownerID2)
}

// MessageAddReactionAtomic mocks base method.
func (m *MockDBHandler) MessageAddReactionAtomic(ctx context.Context, messageID uuid.UUID, reactionJSON string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageAddReactionAtomic", ctx, messageID, reactionJSON)
	ret0, _ := ret[0].(error)
	return ret0
}

// MessageAddReactionAtomic indicates an expected call of MessageAddReactionAtomic.
func (mr *MockDBHandlerMockRecorder) MessageAddReactionAtomic(ctx, messageID, reactionJSON any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageAddReactionAtomic", reflect.TypeOf((*MockDBHandler)(nil).MessageAddReactionAtomic), ctx, messageID, reactionJSON)
}

// MessageCreate mocks base method.
func (m_2 *MockDBHandler) MessageCreate(ctx context.Context, m *message.Message) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "MessageCreate", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// MessageCreate indicates an expected call of MessageCreate.
func (mr *MockDBHandlerMockRecorder) MessageCreate(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageCreate", reflect.TypeOf((*MockDBHandler)(nil).MessageCreate), ctx, m)
}

// MessageDelete mocks base method.
func (m *MockDBHandler) MessageDelete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MessageDelete indicates an expected call of MessageDelete.
func (mr *MockDBHandlerMockRecorder) MessageDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageDelete", reflect.TypeOf((*MockDBHandler)(nil).MessageDelete), ctx, id)
}

// MessageGet mocks base method.
func (m *MockDBHandler) MessageGet(ctx context.Context, id uuid.UUID) (*message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageGet", ctx, id)
	ret0, _ := ret[0].(*message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MessageGet indicates an expected call of MessageGet.
func (mr *MockDBHandlerMockRecorder) MessageGet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageGet", reflect.TypeOf((*MockDBHandler)(nil).MessageGet), ctx, id)
}

// MessageList mocks base method.
func (m *MockDBHandler) MessageList(ctx context.Context, filters map[message.Field]any, token string, size uint64) ([]*message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageList", ctx, filters, token, size)
	ret0, _ := ret[0].([]*message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MessageList indicates an expected call of MessageList.
func (mr *MockDBHandlerMockRecorder) MessageList(ctx, filters, token, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageList", reflect.TypeOf((*MockDBHandler)(nil).MessageList), ctx, filters, token, size)
}

// MessageRemoveReactionAtomic mocks base method.
func (m *MockDBHandler) MessageRemoveReactionAtomic(ctx context.Context, messageID uuid.UUID, emoji, ownerType string, ownerID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageRemoveReactionAtomic", ctx, messageID, emoji, ownerType, ownerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MessageRemoveReactionAtomic indicates an expected call of MessageRemoveReactionAtomic.
func (mr *MockDBHandlerMockRecorder) MessageRemoveReactionAtomic(ctx, messageID, emoji, ownerType, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageRemoveReactionAtomic", reflect.TypeOf((*MockDBHandler)(nil).MessageRemoveReactionAtomic), ctx, messageID, emoji, ownerType, ownerID)
}

// MessageUpdate mocks base method.
func (m *MockDBHandler) MessageUpdate(ctx context.Context, id uuid.UUID, fields map[message.Field]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageUpdate", ctx, id, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// MessageUpdate indicates an expected call of MessageUpdate.
func (mr *MockDBHandlerMockRecorder) MessageUpdate(ctx, id, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageUpdate", reflect.TypeOf((*MockDBHandler)(nil).MessageUpdate), ctx, id, fields)
}

// ParticipantCreate mocks base method.
func (m *MockDBHandler) ParticipantCreate(ctx context.Context, p *participant.Participant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParticipantCreate", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// ParticipantCreate indicates an expected call of ParticipantCreate.
func (mr *MockDBHandlerMockRecorder) ParticipantCreate(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParticipantCreate", reflect.TypeOf((*MockDBHandler)(nil).ParticipantCreate), ctx, p)
}

// ParticipantDelete mocks base method.
func (m *MockDBHandler) ParticipantDelete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParticipantDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ParticipantDelete indicates an expected call of ParticipantDelete.
func (mr *MockDBHandlerMockRecorder) ParticipantDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParticipantDelete", reflect.TypeOf((*MockDBHandler)(nil).ParticipantDelete), ctx, id)
}

// ParticipantGet mocks base method.
func (m *MockDBHandler) ParticipantGet(ctx context.Context, id uuid.UUID) (*participant.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParticipantGet", ctx, id)
	ret0, _ := ret[0].(*participant.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParticipantGet indicates an expected call of ParticipantGet.
func (mr *MockDBHandlerMockRecorder) ParticipantGet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParticipantGet", reflect.TypeOf((*MockDBHandler)(nil).ParticipantGet), ctx, id)
}

// ParticipantList mocks base method.
func (m *MockDBHandler) ParticipantList(ctx context.Context, filters map[participant.Field]any) ([]*participant.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParticipantList", ctx, filters)
	ret0, _ := ret[0].([]*participant.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParticipantList indicates an expected call of ParticipantList.
func (mr *MockDBHandlerMockRecorder) ParticipantList(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParticipantList", reflect.TypeOf((*MockDBHandler)(nil).ParticipantList), ctx, filters)
}

// ParticipantListByChatIDs mocks base method.
func (m *MockDBHandler) ParticipantListByChatIDs(ctx context.Context, chatIDs []uuid.UUID) ([]*participant.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParticipantListByChatIDs", ctx, chatIDs)
	ret0, _ := ret[0].([]*participant.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParticipantListByChatIDs indicates an expected call of ParticipantListByChatIDs.
func (mr *MockDBHandlerMockRecorder) ParticipantListByChatIDs(ctx, chatIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParticipantListByChatIDs", reflect.TypeOf((*MockDBHandler)(nil).ParticipantListByChatIDs), ctx, chatIDs)
}
