// Code generated by MockGen. DO NOT EDIT.
// Source: main.go

// Package accounthandler is a generated GoMock package.
package accounthandler

import (
	context "context"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	gomock "github.com/golang/mock/gomock"
	account "gitlab.com/voipbin/bin-manager/billing-manager.git/models/account"
)

// MockAccountHandler is a mock of AccountHandler interface.
type MockAccountHandler struct {
	ctrl     *gomock.Controller
	recorder *MockAccountHandlerMockRecorder
}

// MockAccountHandlerMockRecorder is the mock recorder for MockAccountHandler.
type MockAccountHandlerMockRecorder struct {
	mock *MockAccountHandler
}

// NewMockAccountHandler creates a new mock instance.
func NewMockAccountHandler(ctrl *gomock.Controller) *MockAccountHandler {
	mock := &MockAccountHandler{ctrl: ctrl}
	mock.recorder = &MockAccountHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountHandler) EXPECT() *MockAccountHandlerMockRecorder {
	return m.recorder
}

// AddBalanceByCustomer mocks base method.
func (m *MockAccountHandler) AddBalanceByCustomer(ctx context.Context, customerID uuid.UUID, balance float32) (*account.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBalanceByCustomer", ctx, customerID, balance)
	ret0, _ := ret[0].(*account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddBalanceByCustomer indicates an expected call of AddBalanceByCustomer.
func (mr *MockAccountHandlerMockRecorder) AddBalanceByCustomer(ctx, customerID, balance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBalanceByCustomer", reflect.TypeOf((*MockAccountHandler)(nil).AddBalanceByCustomer), ctx, customerID, balance)
}

// Create mocks base method.
func (m *MockAccountHandler) Create(ctx context.Context, customerID uuid.UUID) (*account.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, customerID)
	ret0, _ := ret[0].(*account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAccountHandlerMockRecorder) Create(ctx, customerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountHandler)(nil).Create), ctx, customerID)
}

// Get mocks base method.
func (m *MockAccountHandler) Get(ctx context.Context, id uuid.UUID) (*account.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAccountHandlerMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAccountHandler)(nil).Get), ctx, id)
}

// GetByCustomerID mocks base method.
func (m *MockAccountHandler) GetByCustomerID(ctx context.Context, customerID uuid.UUID) (*account.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCustomerID", ctx, customerID)
	ret0, _ := ret[0].(*account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCustomerID indicates an expected call of GetByCustomerID.
func (mr *MockAccountHandlerMockRecorder) GetByCustomerID(ctx, customerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCustomerID", reflect.TypeOf((*MockAccountHandler)(nil).GetByCustomerID), ctx, customerID)
}

// Gets mocks base method.
func (m *MockAccountHandler) Gets(ctx context.Context, size uint64, token string) ([]*account.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gets", ctx, size, token)
	ret0, _ := ret[0].([]*account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Gets indicates an expected call of Gets.
func (mr *MockAccountHandlerMockRecorder) Gets(ctx, size, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gets", reflect.TypeOf((*MockAccountHandler)(nil).Gets), ctx, size, token)
}

// IsValidBalanceByCustomerID mocks base method.
func (m *MockAccountHandler) IsValidBalanceByCustomerID(ctx context.Context, customerID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValidBalanceByCustomerID", ctx, customerID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValidBalanceByCustomerID indicates an expected call of IsValidBalanceByCustomerID.
func (mr *MockAccountHandlerMockRecorder) IsValidBalanceByCustomerID(ctx, customerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValidBalanceByCustomerID", reflect.TypeOf((*MockAccountHandler)(nil).IsValidBalanceByCustomerID), ctx, customerID)
}

// SubstractBalanceByCustomer mocks base method.
func (m *MockAccountHandler) SubstractBalanceByCustomer(ctx context.Context, customerID uuid.UUID, balance float32) (*account.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubstractBalanceByCustomer", ctx, customerID, balance)
	ret0, _ := ret[0].(*account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubstractBalanceByCustomer indicates an expected call of SubstractBalanceByCustomer.
func (mr *MockAccountHandlerMockRecorder) SubstractBalanceByCustomer(ctx, customerID, balance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubstractBalanceByCustomer", reflect.TypeOf((*MockAccountHandler)(nil).SubstractBalanceByCustomer), ctx, customerID, balance)
}
