apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-manager
  labels:
    app: rag-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-manager
  template:
    metadata:
      labels:
        app: rag-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "2112"
    spec:
      containers:
        - name: rag-manager
          image: rag-manager-image
          command:
            - './rag-manager'
          env:
            - name: RABBITMQ_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: bin-manager-secrets
                  key: RABBITMQ_ADDRESS
            - name: GCP_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: bin-manager-secrets
                  key: GCP_PROJECT_ID
            - name: GCP_LOCATION
              valueFrom:
                secretKeyRef:
                  name: bin-manager-secrets
                  key: GCP_LOCATION
            - name: GOOGLE_EMBEDDING_MODEL
              value: "text-embedding-004"
            - name: RAG_TOP_K
              value: "5"
            - name: PROMETHEUS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: bin-manager-secrets
                  key: PROMETHEUS_ENDPOINT
            - name: PROMETHEUS_LISTEN_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: bin-manager-secrets
                  key: PROMETHEUS_LISTEN_ADDRESS
            - name: POSTGRESQL_DSN
              valueFrom:
                secretKeyRef:
                  name: bin-manager-secrets
                  key: DATABASE_DSN_POSTGRES
          ports:
            - name: metrics
              protocol: "TCP"
              containerPort: 2112
          resources:
            requests:
              cpu: "10m"
              memory: "13M"
            limits:
              cpu: "100m"
              memory: "128M"
