// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -package dbhandler -destination ./mock_main.go -source main.go -build_flags=-mod=mod
//

// Package dbhandler is a generated GoMock package.
package dbhandler

import (
	context "context"
	message "monorepo/bin-webchat-manager/models/message"
	session "monorepo/bin-webchat-manager/models/session"
	widget "monorepo/bin-webchat-manager/models/widget"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDBHandler is a mock of DBHandler interface.
type MockDBHandler struct {
	ctrl     *gomock.Controller
	recorder *MockDBHandlerMockRecorder
	isgomock struct{}
}

// MockDBHandlerMockRecorder is the mock recorder for MockDBHandler.
type MockDBHandlerMockRecorder struct {
	mock *MockDBHandler
}

// NewMockDBHandler creates a new mock instance.
func NewMockDBHandler(ctrl *gomock.Controller) *MockDBHandler {
	mock := &MockDBHandler{ctrl: ctrl}
	mock.recorder = &MockDBHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBHandler) EXPECT() *MockDBHandlerMockRecorder {
	return m.recorder
}

// MessageCreate mocks base method.
func (m_2 *MockDBHandler) MessageCreate(ctx context.Context, m *message.Message) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "MessageCreate", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// MessageCreate indicates an expected call of MessageCreate.
func (mr *MockDBHandlerMockRecorder) MessageCreate(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageCreate", reflect.TypeOf((*MockDBHandler)(nil).MessageCreate), ctx, m)
}

// MessageDelete mocks base method.
func (m *MockDBHandler) MessageDelete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MessageDelete indicates an expected call of MessageDelete.
func (mr *MockDBHandlerMockRecorder) MessageDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageDelete", reflect.TypeOf((*MockDBHandler)(nil).MessageDelete), ctx, id)
}

// MessageGet mocks base method.
func (m *MockDBHandler) MessageGet(ctx context.Context, id uuid.UUID) (*message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageGet", ctx, id)
	ret0, _ := ret[0].(*message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MessageGet indicates an expected call of MessageGet.
func (mr *MockDBHandlerMockRecorder) MessageGet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageGet", reflect.TypeOf((*MockDBHandler)(nil).MessageGet), ctx, id)
}

// MessageList mocks base method.
func (m *MockDBHandler) MessageList(ctx context.Context, size uint64, token string, filters map[message.Field]any) ([]*message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageList", ctx, size, token, filters)
	ret0, _ := ret[0].([]*message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MessageList indicates an expected call of MessageList.
func (mr *MockDBHandlerMockRecorder) MessageList(ctx, size, token, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageList", reflect.TypeOf((*MockDBHandler)(nil).MessageList), ctx, size, token, filters)
}

// SessionCreate mocks base method.
func (m *MockDBHandler) SessionCreate(ctx context.Context, s *session.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionCreate", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// SessionCreate indicates an expected call of SessionCreate.
func (mr *MockDBHandlerMockRecorder) SessionCreate(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionCreate", reflect.TypeOf((*MockDBHandler)(nil).SessionCreate), ctx, s)
}

// SessionDelete mocks base method.
func (m *MockDBHandler) SessionDelete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SessionDelete indicates an expected call of SessionDelete.
func (mr *MockDBHandlerMockRecorder) SessionDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionDelete", reflect.TypeOf((*MockDBHandler)(nil).SessionDelete), ctx, id)
}

// SessionGet mocks base method.
func (m *MockDBHandler) SessionGet(ctx context.Context, id uuid.UUID) (*session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionGet", ctx, id)
	ret0, _ := ret[0].(*session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SessionGet indicates an expected call of SessionGet.
func (mr *MockDBHandlerMockRecorder) SessionGet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionGet", reflect.TypeOf((*MockDBHandler)(nil).SessionGet), ctx, id)
}

// SessionList mocks base method.
func (m *MockDBHandler) SessionList(ctx context.Context, size uint64, token string, filters map[session.Field]any) ([]*session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionList", ctx, size, token, filters)
	ret0, _ := ret[0].([]*session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SessionList indicates an expected call of SessionList.
func (mr *MockDBHandlerMockRecorder) SessionList(ctx, size, token, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionList", reflect.TypeOf((*MockDBHandler)(nil).SessionList), ctx, size, token, filters)
}

// SessionUpdate mocks base method.
func (m *MockDBHandler) SessionUpdate(ctx context.Context, id uuid.UUID, fields map[session.Field]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionUpdate", ctx, id, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// SessionUpdate indicates an expected call of SessionUpdate.
func (mr *MockDBHandlerMockRecorder) SessionUpdate(ctx, id, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionUpdate", reflect.TypeOf((*MockDBHandler)(nil).SessionUpdate), ctx, id, fields)
}

// WidgetCreate mocks base method.
func (m *MockDBHandler) WidgetCreate(ctx context.Context, w *widget.Widget) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WidgetCreate", ctx, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// WidgetCreate indicates an expected call of WidgetCreate.
func (mr *MockDBHandlerMockRecorder) WidgetCreate(ctx, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WidgetCreate", reflect.TypeOf((*MockDBHandler)(nil).WidgetCreate), ctx, w)
}

// WidgetDelete mocks base method.
func (m *MockDBHandler) WidgetDelete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WidgetDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// WidgetDelete indicates an expected call of WidgetDelete.
func (mr *MockDBHandlerMockRecorder) WidgetDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WidgetDelete", reflect.TypeOf((*MockDBHandler)(nil).WidgetDelete), ctx, id)
}

// WidgetGet mocks base method.
func (m *MockDBHandler) WidgetGet(ctx context.Context, id uuid.UUID) (*widget.Widget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WidgetGet", ctx, id)
	ret0, _ := ret[0].(*widget.Widget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WidgetGet indicates an expected call of WidgetGet.
func (mr *MockDBHandlerMockRecorder) WidgetGet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WidgetGet", reflect.TypeOf((*MockDBHandler)(nil).WidgetGet), ctx, id)
}

// WidgetList mocks base method.
func (m *MockDBHandler) WidgetList(ctx context.Context, size uint64, token string, filters map[widget.Field]any) ([]*widget.Widget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WidgetList", ctx, size, token, filters)
	ret0, _ := ret[0].([]*widget.Widget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WidgetList indicates an expected call of WidgetList.
func (mr *MockDBHandlerMockRecorder) WidgetList(ctx, size, token, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WidgetList", reflect.TypeOf((*MockDBHandler)(nil).WidgetList), ctx, size, token, filters)
}

// WidgetUpdate mocks base method.
func (m *MockDBHandler) WidgetUpdate(ctx context.Context, id uuid.UUID, fields map[widget.Field]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WidgetUpdate", ctx, id, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// WidgetUpdate indicates an expected call of WidgetUpdate.
func (mr *MockDBHandlerMockRecorder) WidgetUpdate(ctx, id, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WidgetUpdate", reflect.TypeOf((*MockDBHandler)(nil).WidgetUpdate), ctx, id, fields)
}
