// Code generated by MockGen. DO NOT EDIT.
// Source: main.go

// Package cachehandler is a generated GoMock package.
package cachehandler

import (
	context "context"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	gomock "github.com/golang/mock/gomock"
	agent "gitlab.com/voipbin/bin-manager/agent-manager.git/models/agent"
	agentcall "gitlab.com/voipbin/bin-manager/agent-manager.git/models/agentcall"
	agentdial "gitlab.com/voipbin/bin-manager/agent-manager.git/models/agentdial"
	tag "gitlab.com/voipbin/bin-manager/agent-manager.git/models/tag"
)

// MockCacheHandler is a mock of CacheHandler interface.
type MockCacheHandler struct {
	ctrl     *gomock.Controller
	recorder *MockCacheHandlerMockRecorder
}

// MockCacheHandlerMockRecorder is the mock recorder for MockCacheHandler.
type MockCacheHandlerMockRecorder struct {
	mock *MockCacheHandler
}

// NewMockCacheHandler creates a new mock instance.
func NewMockCacheHandler(ctrl *gomock.Controller) *MockCacheHandler {
	mock := &MockCacheHandler{ctrl: ctrl}
	mock.recorder = &MockCacheHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheHandler) EXPECT() *MockCacheHandlerMockRecorder {
	return m.recorder
}

// AgentCallGet mocks base method.
func (m *MockCacheHandler) AgentCallGet(ctx context.Context, id uuid.UUID) (*agentcall.AgentCall, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentCallGet", ctx, id)
	ret0, _ := ret[0].(*agentcall.AgentCall)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AgentCallGet indicates an expected call of AgentCallGet.
func (mr *MockCacheHandlerMockRecorder) AgentCallGet(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentCallGet", reflect.TypeOf((*MockCacheHandler)(nil).AgentCallGet), ctx, id)
}

// AgentCallSet mocks base method.
func (m *MockCacheHandler) AgentCallSet(ctx context.Context, u *agentcall.AgentCall) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentCallSet", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// AgentCallSet indicates an expected call of AgentCallSet.
func (mr *MockCacheHandlerMockRecorder) AgentCallSet(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentCallSet", reflect.TypeOf((*MockCacheHandler)(nil).AgentCallSet), ctx, u)
}

// AgentDialGet mocks base method.
func (m *MockCacheHandler) AgentDialGet(ctx context.Context, id uuid.UUID) (*agentdial.AgentDial, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentDialGet", ctx, id)
	ret0, _ := ret[0].(*agentdial.AgentDial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AgentDialGet indicates an expected call of AgentDialGet.
func (mr *MockCacheHandlerMockRecorder) AgentDialGet(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentDialGet", reflect.TypeOf((*MockCacheHandler)(nil).AgentDialGet), ctx, id)
}

// AgentDialSet mocks base method.
func (m *MockCacheHandler) AgentDialSet(ctx context.Context, u *agentdial.AgentDial) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentDialSet", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// AgentDialSet indicates an expected call of AgentDialSet.
func (mr *MockCacheHandlerMockRecorder) AgentDialSet(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentDialSet", reflect.TypeOf((*MockCacheHandler)(nil).AgentDialSet), ctx, u)
}

// AgentGet mocks base method.
func (m *MockCacheHandler) AgentGet(ctx context.Context, id uuid.UUID) (*agent.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentGet", ctx, id)
	ret0, _ := ret[0].(*agent.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AgentGet indicates an expected call of AgentGet.
func (mr *MockCacheHandlerMockRecorder) AgentGet(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentGet", reflect.TypeOf((*MockCacheHandler)(nil).AgentGet), ctx, id)
}

// AgentSet mocks base method.
func (m *MockCacheHandler) AgentSet(ctx context.Context, u *agent.Agent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentSet", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// AgentSet indicates an expected call of AgentSet.
func (mr *MockCacheHandlerMockRecorder) AgentSet(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentSet", reflect.TypeOf((*MockCacheHandler)(nil).AgentSet), ctx, u)
}

// Connect mocks base method.
func (m *MockCacheHandler) Connect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockCacheHandlerMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockCacheHandler)(nil).Connect))
}

// TagGet mocks base method.
func (m *MockCacheHandler) TagGet(ctx context.Context, id uuid.UUID) (*tag.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagGet", ctx, id)
	ret0, _ := ret[0].(*tag.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagGet indicates an expected call of TagGet.
func (mr *MockCacheHandlerMockRecorder) TagGet(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagGet", reflect.TypeOf((*MockCacheHandler)(nil).TagGet), ctx, id)
}

// TagSet mocks base method.
func (m *MockCacheHandler) TagSet(ctx context.Context, u *tag.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagSet", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// TagSet indicates an expected call of TagSet.
func (mr *MockCacheHandlerMockRecorder) TagSet(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagSet", reflect.TypeOf((*MockCacheHandler)(nil).TagSet), ctx, u)
}
