// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -package teamhandler -destination ./mock_main.go -source main.go -build_flags=-mod=mod
//

// Package teamhandler is a generated GoMock package.
package teamhandler

import (
	context "context"
	team "monorepo/bin-ai-manager/models/team"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTeamHandler is a mock of TeamHandler interface.
type MockTeamHandler struct {
	ctrl     *gomock.Controller
	recorder *MockTeamHandlerMockRecorder
	isgomock struct{}
}

// MockTeamHandlerMockRecorder is the mock recorder for MockTeamHandler.
type MockTeamHandlerMockRecorder struct {
	mock *MockTeamHandler
}

// NewMockTeamHandler creates a new mock instance.
func NewMockTeamHandler(ctrl *gomock.Controller) *MockTeamHandler {
	mock := &MockTeamHandler{ctrl: ctrl}
	mock.recorder = &MockTeamHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamHandler) EXPECT() *MockTeamHandlerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTeamHandler) Create(ctx context.Context, customerID uuid.UUID, name, detail string, startMemberID uuid.UUID, members []team.Member, parameter map[string]any) (*team.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, customerID, name, detail, startMemberID, members, parameter)
	ret0, _ := ret[0].(*team.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTeamHandlerMockRecorder) Create(ctx, customerID, name, detail, startMemberID, members, parameter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTeamHandler)(nil).Create), ctx, customerID, name, detail, startMemberID, members, parameter)
}

// Delete mocks base method.
func (m *MockTeamHandler) Delete(ctx context.Context, id uuid.UUID) (*team.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*team.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockTeamHandlerMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTeamHandler)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockTeamHandler) Get(ctx context.Context, id uuid.UUID) (*team.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*team.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTeamHandlerMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTeamHandler)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockTeamHandler) List(ctx context.Context, size uint64, token string, filters map[team.Field]any) ([]*team.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, size, token, filters)
	ret0, _ := ret[0].([]*team.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTeamHandlerMockRecorder) List(ctx, size, token, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTeamHandler)(nil).List), ctx, size, token, filters)
}

// Update mocks base method.
func (m *MockTeamHandler) Update(ctx context.Context, id uuid.UUID, name, detail string, startMemberID uuid.UUID, members []team.Member, parameter map[string]any) (*team.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, name, detail, startMemberID, members, parameter)
	ret0, _ := ret[0].(*team.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTeamHandlerMockRecorder) Update(ctx, id, name, detail, startMemberID, members, parameter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTeamHandler)(nil).Update), ctx, id, name, detail, startMemberID, members, parameter)
}
