// Code generated by MockGen. DO NOT EDIT.
// Source: ./main.go

// Package notifyhandler is a generated GoMock package.
package notifyhandler

import (
	gomock "github.com/golang/mock/gomock"
	call "gitlab.com/voipbin/bin-manager/call-manager.git/models/call"
	reflect "reflect"
)

// MockNotifyHandler is a mock of NotifyHandler interface
type MockNotifyHandler struct {
	ctrl     *gomock.Controller
	recorder *MockNotifyHandlerMockRecorder
}

// MockNotifyHandlerMockRecorder is the mock recorder for MockNotifyHandler
type MockNotifyHandlerMockRecorder struct {
	mock *MockNotifyHandler
}

// NewMockNotifyHandler creates a new mock instance
func NewMockNotifyHandler(ctrl *gomock.Controller) *MockNotifyHandler {
	mock := &MockNotifyHandler{ctrl: ctrl}
	mock.recorder = &MockNotifyHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNotifyHandler) EXPECT() *MockNotifyHandlerMockRecorder {
	return m.recorder
}

// CallCreated mocks base method
func (m *MockNotifyHandler) CallCreated(c *call.Call) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CallCreated", c)
}

// CallCreated indicates an expected call of CallCreated
func (mr *MockNotifyHandlerMockRecorder) CallCreated(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallCreated", reflect.TypeOf((*MockNotifyHandler)(nil).CallCreated), c)
}

// CallUpdated mocks base method
func (m *MockNotifyHandler) CallUpdated(c *call.Call) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CallUpdated", c)
}

// CallUpdated indicates an expected call of CallUpdated
func (mr *MockNotifyHandlerMockRecorder) CallUpdated(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallUpdated", reflect.TypeOf((*MockNotifyHandler)(nil).CallUpdated), c)
}

// CallHungup mocks base method
func (m *MockNotifyHandler) CallHungup(c *call.Call) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CallHungup", c)
}

// CallHungup indicates an expected call of CallHungup
func (mr *MockNotifyHandlerMockRecorder) CallHungup(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallHungup", reflect.TypeOf((*MockNotifyHandler)(nil).CallHungup), c)
}
