// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -package telnyxclient -destination ./mock_main.go -source main.go -build_flags=-mod=mod
//

// Package telnyxclient is a generated GoMock package.
package telnyxclient

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTelnyxClient is a mock of TelnyxClient interface.
type MockTelnyxClient struct {
	ctrl     *gomock.Controller
	recorder *MockTelnyxClientMockRecorder
	isgomock struct{}
}

// MockTelnyxClientMockRecorder is the mock recorder for MockTelnyxClient.
type MockTelnyxClientMockRecorder struct {
	mock *MockTelnyxClient
}

// NewMockTelnyxClient creates a new mock instance.
func NewMockTelnyxClient(ctrl *gomock.Controller) *MockTelnyxClient {
	mock := &MockTelnyxClient{ctrl: ctrl}
	mock.recorder = &MockTelnyxClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelnyxClient) EXPECT() *MockTelnyxClientMockRecorder {
	return m.recorder
}

// CreateFQDNConnection mocks base method.
func (m *MockTelnyxClient) CreateFQDNConnection(ctx context.Context, name, profileID, userName, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFQDNConnection", ctx, name, profileID, userName, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFQDNConnection indicates an expected call of CreateFQDNConnection.
func (mr *MockTelnyxClientMockRecorder) CreateFQDNConnection(ctx, name, profileID, userName, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFQDNConnection", reflect.TypeOf((*MockTelnyxClient)(nil).CreateFQDNConnection), ctx, name, profileID, userName, password)
}

// CreateOutboundVoiceProfile mocks base method.
func (m *MockTelnyxClient) CreateOutboundVoiceProfile(ctx context.Context, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOutboundVoiceProfile", ctx, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOutboundVoiceProfile indicates an expected call of CreateOutboundVoiceProfile.
func (mr *MockTelnyxClientMockRecorder) CreateOutboundVoiceProfile(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOutboundVoiceProfile", reflect.TypeOf((*MockTelnyxClient)(nil).CreateOutboundVoiceProfile), ctx, name)
}

// DeleteFQDN mocks base method.
func (m *MockTelnyxClient) DeleteFQDN(ctx context.Context, fqdnID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFQDN", ctx, fqdnID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFQDN indicates an expected call of DeleteFQDN.
func (mr *MockTelnyxClientMockRecorder) DeleteFQDN(ctx, fqdnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFQDN", reflect.TypeOf((*MockTelnyxClient)(nil).DeleteFQDN), ctx, fqdnID)
}

// DeleteFQDNConnection mocks base method.
func (m *MockTelnyxClient) DeleteFQDNConnection(ctx context.Context, connID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFQDNConnection", ctx, connID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFQDNConnection indicates an expected call of DeleteFQDNConnection.
func (mr *MockTelnyxClientMockRecorder) DeleteFQDNConnection(ctx, connID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFQDNConnection", reflect.TypeOf((*MockTelnyxClient)(nil).DeleteFQDNConnection), ctx, connID)
}

// DeleteOutboundVoiceProfile mocks base method.
func (m *MockTelnyxClient) DeleteOutboundVoiceProfile(ctx context.Context, profileID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOutboundVoiceProfile", ctx, profileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOutboundVoiceProfile indicates an expected call of DeleteOutboundVoiceProfile.
func (mr *MockTelnyxClientMockRecorder) DeleteOutboundVoiceProfile(ctx, profileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOutboundVoiceProfile", reflect.TypeOf((*MockTelnyxClient)(nil).DeleteOutboundVoiceProfile), ctx, profileID)
}

// RegisterFQDN mocks base method.
func (m *MockTelnyxClient) RegisterFQDN(ctx context.Context, connID, fqdn string, port int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterFQDN", ctx, connID, fqdn, port)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterFQDN indicates an expected call of RegisterFQDN.
func (mr *MockTelnyxClientMockRecorder) RegisterFQDN(ctx, connID, fqdn, port any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterFQDN", reflect.TypeOf((*MockTelnyxClient)(nil).RegisterFQDN), ctx, connID, fqdn, port)
}

// ValidateKey mocks base method.
func (m *MockTelnyxClient) ValidateKey(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateKey", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateKey indicates an expected call of ValidateKey.
func (mr *MockTelnyxClientMockRecorder) ValidateKey(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateKey", reflect.TypeOf((*MockTelnyxClient)(nil).ValidateKey), ctx)
}
