apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-manager
  labels:
    app: ai-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-manager
  template:
    metadata:
      labels:
        app: ai-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "2112"
    spec:
      containers:
        - name: ai-manager
          image: ai-manager-image
          command:
            - './ai-manager'
          env:
            - name: DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: DATABASE_DSN_BIN
            - name: PROMETHEUS_ENDPOINT
              value: "/metrics"
            - name: PROMETHEUS_LISTEN_ADDRESS
              value: ":2112"
            - name: RABBITMQ_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: RABBITMQ_ADDRESS
            - name: REDIS_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: REDIS_ADDRESS
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: REDIS_PASSWORD
            - name: REDIS_DATABASE
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: REDIS_DATABASE
            - name: ENGINE_KEY_CHATGPT
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: OPENAI_API_KEY
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: GOOGLE_API_KEY
            - name: CLICKHOUSE_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: CLICKHOUSE_ADDRESS
          ports:
            - name: metrics
              protocol: "TCP"
              containerPort: 2112
          resources:
            requests:
              cpu: "4m"
              memory: "4M"
            limits:
              cpu: "40m"
              memory: "40M"
