apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-manager
  labels:
    app: ai-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-manager
  template:
    metadata:
      labels:
        app: ai-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "2112"
    spec:
      containers:
        - name: ai-manager
          image: ai-manager-image
          command:
            - './ai-manager'
          env:
            - name: DATABASE_DSN
              value: ${DATABASE_DSN}
            - name: PROMETHEUS_ENDPOINT
              value: "/metrics"
            - name: PROMETHEUS_LISTEN_ADDRESS
              value: ":2112"
            - name: RABBITMQ_ADDRESS
              value: ${RABBITMQ_ADDRESS}
            - name: REDIS_ADDRESS
              value: ${REDIS_ADDRESS}
            - name: REDIS_PASSWORD
              value: ${REDIS_PASSWORD}
            - name: REDIS_DATABASE
              value: "1"
            - name: ENGINE_KEY_CHATGPT
              value: "${AUTHTOKEN_OPENAI}"
          ports:
            - name: metrics
              protocol: "TCP"
              containerPort: 2112
          resources:
            limits:
              cpu: "40m"
              memory: "40M"
