apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-manager
  labels:
    app: storage-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storage-manager
  template:
    metadata:
      labels:
        app: storage-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "2112"
    spec:
      containers:
        - name: storage-manager
          image: storage-manager-image
          command:
            - './storage-manager'
          env:
            - name: DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: DATABASE_DSN_BIN
            - name: PROMETHEUS_ENDPOINT
              value: "/metrics"
            - name: PROMETHEUS_LISTEN_ADDRESS
              value: ":2112"
            - name: RABBITMQ_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: RABBITMQ_ADDRESS
            - name: REDIS_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: REDIS_ADDRESS
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: REDIS_PASSWORD
            - name: REDIS_DATABASE
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: REDIS_DATABASE
            - name: GCP_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: GCP_PROJECT_ID
            - name: GCP_BUCKET_NAME_TMP
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: GCP_BUCKET_NAME_TMP
            - name: GCP_BUCKET_NAME_MEDIA
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: GCP_BUCKET_NAME_MEDIA
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: JWT_KEY
            - name: CLICKHOUSE_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: CLICKHOUSE_ADDRESS
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/google/service-account.json"
          volumeMounts:
            - name: google-application-credentials
              mountPath: /var/secrets/google
              readOnly: true
          ports:
            - name: metrics
              protocol: "TCP"
              containerPort: 2112
          resources:
            requests:
              cpu: "10m"
              memory: "10M"
            limits:
              cpu: "100m"
              memory: "100M"
      volumes:
        - name: google-application-credentials
          secret:
            secretName: voipbin
            items:
              - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
                path: service-account.json
