apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-manager
  labels:
    app: storage-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storage-manager
  template:
    metadata:
      labels:
        app: storage-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "2112"
    spec:
      containers:
        - name: storage-manager
          image: storage-manager-image
          command:
            - './storage-manager'
          env:
            - name: DATABASE_DSN
              value: ${DATABASE_DSN}
            - name: PROMETHEUS_ENDPOINT
              value: "/metrics"
            - name: PROMETHEUS_LISTEN_ADDRESS
              value: ":2112"
            - name: RABBITMQ_ADDRESS
              value: ${RABBITMQ_ADDRESS}
            - name: REDIS_ADDRESS
              value: ${REDIS_ADDRESS}
            - name: REDIS_PASSWORD
              value: ${REDIS_PASSWORD}
            - name: REDIS_DATABASE
              value: "1"
            - name: GCP_CREDENTIAL_BASE64
              value: ${GCP_SERVICE_ACCOUNT_BASE64}
            - name: GCP_PROJECT_ID
              value: ${GCP_PROJECT_ID}
            - name: GCP_BUCKET_NAME_TMP
              value: ${GCP_BUCKET_NAME_TMP}
            - name: GCP_BUCKET_NAME_MEDIA
              value: ${GCP_BUCKET_NAME_MEDIA}
            - name: JWT_KEY
              value: ${JWT_KEY}
          ports:
            - name: metrics
              protocol: "TCP"
              containerPort: 2112
          resources:
            limits:
              cpu: "100m"
              memory: "100M"
