// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -package builderhandler -destination ./mock_main.go -source main.go -build_flags=-mod=mod
//

// Package builderhandler is a generated GoMock package.
package builderhandler

import (
	context "context"
	builder "monorepo/bin-ai-manager/models/builder"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockBuilderHandler is a mock of BuilderHandler interface.
type MockBuilderHandler struct {
	ctrl     *gomock.Controller
	recorder *MockBuilderHandlerMockRecorder
	isgomock struct{}
}

// MockBuilderHandlerMockRecorder is the mock recorder for MockBuilderHandler.
type MockBuilderHandlerMockRecorder struct {
	mock *MockBuilderHandler
}

// NewMockBuilderHandler creates a new mock instance.
func NewMockBuilderHandler(ctrl *gomock.Controller) *MockBuilderHandler {
	mock := &MockBuilderHandler{ctrl: ctrl}
	mock.recorder = &MockBuilderHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuilderHandler) EXPECT() *MockBuilderHandlerMockRecorder {
	return m.recorder
}

// Chat mocks base method.
func (m *MockBuilderHandler) Chat(ctx context.Context, customerID uuid.UUID, req *builder.ChatRequest) (*builder.ChatResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat", ctx, customerID, req)
	ret0, _ := ret[0].(*builder.ChatResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Chat indicates an expected call of Chat.
func (mr *MockBuilderHandlerMockRecorder) Chat(ctx, customerID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockBuilderHandler)(nil).Chat), ctx, customerID, req)
}

// Status mocks base method.
func (m *MockBuilderHandler) Status() *builder.StatusResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(*builder.StatusResponse)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockBuilderHandlerMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockBuilderHandler)(nil).Status))
}
