// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -package dbhandler -destination ./mock_main.go -source main.go -build_flags=-mod=mod
//

// Package dbhandler is a generated GoMock package.
package dbhandler

import (
	context "context"
	ai "monorepo/bin-ai-manager/models/ai"
	aicall "monorepo/bin-ai-manager/models/aicall"
	message "monorepo/bin-ai-manager/models/message"
	summary "monorepo/bin-ai-manager/models/summary"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDBHandler is a mock of DBHandler interface.
type MockDBHandler struct {
	ctrl     *gomock.Controller
	recorder *MockDBHandlerMockRecorder
	isgomock struct{}
}

// MockDBHandlerMockRecorder is the mock recorder for MockDBHandler.
type MockDBHandlerMockRecorder struct {
	mock *MockDBHandler
}

// NewMockDBHandler creates a new mock instance.
func NewMockDBHandler(ctrl *gomock.Controller) *MockDBHandler {
	mock := &MockDBHandler{ctrl: ctrl}
	mock.recorder = &MockDBHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBHandler) EXPECT() *MockDBHandlerMockRecorder {
	return m.recorder
}

// AICreate mocks base method.
func (m *MockDBHandler) AICreate(ctx context.Context, c *ai.AI) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AICreate", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// AICreate indicates an expected call of AICreate.
func (mr *MockDBHandlerMockRecorder) AICreate(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AICreate", reflect.TypeOf((*MockDBHandler)(nil).AICreate), ctx, c)
}

// AIDelete mocks base method.
func (m *MockDBHandler) AIDelete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AIDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// AIDelete indicates an expected call of AIDelete.
func (mr *MockDBHandlerMockRecorder) AIDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AIDelete", reflect.TypeOf((*MockDBHandler)(nil).AIDelete), ctx, id)
}

// AIGet mocks base method.
func (m *MockDBHandler) AIGet(ctx context.Context, id uuid.UUID) (*ai.AI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AIGet", ctx, id)
	ret0, _ := ret[0].(*ai.AI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AIGet indicates an expected call of AIGet.
func (mr *MockDBHandlerMockRecorder) AIGet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AIGet", reflect.TypeOf((*MockDBHandler)(nil).AIGet), ctx, id)
}

// AIList mocks base method.
func (m *MockDBHandler) AIList(ctx context.Context, size uint64, token string, filters map[ai.Field]any) ([]*ai.AI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AIList", ctx, size, token, filters)
	ret0, _ := ret[0].([]*ai.AI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AIList indicates an expected call of AIList.
func (mr *MockDBHandlerMockRecorder) AIList(ctx, size, token, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AIList", reflect.TypeOf((*MockDBHandler)(nil).AIList), ctx, size, token, filters)
}

// AIUpdate mocks base method.
func (m *MockDBHandler) AIUpdate(ctx context.Context, id uuid.UUID, fields map[ai.Field]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AIUpdate", ctx, id, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// AIUpdate indicates an expected call of AIUpdate.
func (mr *MockDBHandlerMockRecorder) AIUpdate(ctx, id, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AIUpdate", reflect.TypeOf((*MockDBHandler)(nil).AIUpdate), ctx, id, fields)
}

// AIcallCreate mocks base method.
func (m *MockDBHandler) AIcallCreate(ctx context.Context, cb *aicall.AIcall) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AIcallCreate", ctx, cb)
	ret0, _ := ret[0].(error)
	return ret0
}

// AIcallCreate indicates an expected call of AIcallCreate.
func (mr *MockDBHandlerMockRecorder) AIcallCreate(ctx, cb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AIcallCreate", reflect.TypeOf((*MockDBHandler)(nil).AIcallCreate), ctx, cb)
}

// AIcallDelete mocks base method.
func (m *MockDBHandler) AIcallDelete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AIcallDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// AIcallDelete indicates an expected call of AIcallDelete.
func (mr *MockDBHandlerMockRecorder) AIcallDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AIcallDelete", reflect.TypeOf((*MockDBHandler)(nil).AIcallDelete), ctx, id)
}

// AIcallGet mocks base method.
func (m *MockDBHandler) AIcallGet(ctx context.Context, id uuid.UUID) (*aicall.AIcall, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AIcallGet", ctx, id)
	ret0, _ := ret[0].(*aicall.AIcall)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AIcallGet indicates an expected call of AIcallGet.
func (mr *MockDBHandlerMockRecorder) AIcallGet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AIcallGet", reflect.TypeOf((*MockDBHandler)(nil).AIcallGet), ctx, id)
}

// AIcallGetByReferenceID mocks base method.
func (m *MockDBHandler) AIcallGetByReferenceID(ctx context.Context, referenceID uuid.UUID) (*aicall.AIcall, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AIcallGetByReferenceID", ctx, referenceID)
	ret0, _ := ret[0].(*aicall.AIcall)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AIcallGetByReferenceID indicates an expected call of AIcallGetByReferenceID.
func (mr *MockDBHandlerMockRecorder) AIcallGetByReferenceID(ctx, referenceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AIcallGetByReferenceID", reflect.TypeOf((*MockDBHandler)(nil).AIcallGetByReferenceID), ctx, referenceID)
}

// AIcallList mocks base method.
func (m *MockDBHandler) AIcallList(ctx context.Context, size uint64, token string, filters map[aicall.Field]any) ([]*aicall.AIcall, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AIcallList", ctx, size, token, filters)
	ret0, _ := ret[0].([]*aicall.AIcall)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AIcallList indicates an expected call of AIcallList.
func (mr *MockDBHandlerMockRecorder) AIcallList(ctx, size, token, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AIcallList", reflect.TypeOf((*MockDBHandler)(nil).AIcallList), ctx, size, token, filters)
}

// AIcallUpdate mocks base method.
func (m *MockDBHandler) AIcallUpdate(ctx context.Context, id uuid.UUID, fields map[aicall.Field]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AIcallUpdate", ctx, id, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// AIcallUpdate indicates an expected call of AIcallUpdate.
func (mr *MockDBHandlerMockRecorder) AIcallUpdate(ctx, id, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AIcallUpdate", reflect.TypeOf((*MockDBHandler)(nil).AIcallUpdate), ctx, id, fields)
}

// MessageCreate mocks base method.
func (m *MockDBHandler) MessageCreate(ctx context.Context, c *message.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageCreate", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// MessageCreate indicates an expected call of MessageCreate.
func (mr *MockDBHandlerMockRecorder) MessageCreate(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageCreate", reflect.TypeOf((*MockDBHandler)(nil).MessageCreate), ctx, c)
}

// MessageDelete mocks base method.
func (m *MockDBHandler) MessageDelete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MessageDelete indicates an expected call of MessageDelete.
func (mr *MockDBHandlerMockRecorder) MessageDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageDelete", reflect.TypeOf((*MockDBHandler)(nil).MessageDelete), ctx, id)
}

// MessageGet mocks base method.
func (m *MockDBHandler) MessageGet(ctx context.Context, id uuid.UUID) (*message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageGet", ctx, id)
	ret0, _ := ret[0].(*message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MessageGet indicates an expected call of MessageGet.
func (mr *MockDBHandlerMockRecorder) MessageGet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageGet", reflect.TypeOf((*MockDBHandler)(nil).MessageGet), ctx, id)
}

// MessageList mocks base method.
func (m *MockDBHandler) MessageList(ctx context.Context, size uint64, token string, filters map[message.Field]any) ([]*message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageList", ctx, size, token, filters)
	ret0, _ := ret[0].([]*message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MessageList indicates an expected call of MessageList.
func (mr *MockDBHandlerMockRecorder) MessageList(ctx, size, token, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageList", reflect.TypeOf((*MockDBHandler)(nil).MessageList), ctx, size, token, filters)
}

// SummaryCreate mocks base method.
func (m *MockDBHandler) SummaryCreate(ctx context.Context, c *summary.Summary) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SummaryCreate", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// SummaryCreate indicates an expected call of SummaryCreate.
func (mr *MockDBHandlerMockRecorder) SummaryCreate(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SummaryCreate", reflect.TypeOf((*MockDBHandler)(nil).SummaryCreate), ctx, c)
}

// SummaryDelete mocks base method.
func (m *MockDBHandler) SummaryDelete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SummaryDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SummaryDelete indicates an expected call of SummaryDelete.
func (mr *MockDBHandlerMockRecorder) SummaryDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SummaryDelete", reflect.TypeOf((*MockDBHandler)(nil).SummaryDelete), ctx, id)
}

// SummaryGet mocks base method.
func (m *MockDBHandler) SummaryGet(ctx context.Context, id uuid.UUID) (*summary.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SummaryGet", ctx, id)
	ret0, _ := ret[0].(*summary.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SummaryGet indicates an expected call of SummaryGet.
func (mr *MockDBHandlerMockRecorder) SummaryGet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SummaryGet", reflect.TypeOf((*MockDBHandler)(nil).SummaryGet), ctx, id)
}

// SummaryList mocks base method.
func (m *MockDBHandler) SummaryList(ctx context.Context, size uint64, token string, filters map[summary.Field]any) ([]*summary.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SummaryList", ctx, size, token, filters)
	ret0, _ := ret[0].([]*summary.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SummaryList indicates an expected call of SummaryList.
func (mr *MockDBHandlerMockRecorder) SummaryList(ctx, size, token, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SummaryList", reflect.TypeOf((*MockDBHandler)(nil).SummaryList), ctx, size, token, filters)
}

// SummaryUpdate mocks base method.
func (m *MockDBHandler) SummaryUpdate(ctx context.Context, id uuid.UUID, fields map[summary.Field]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SummaryUpdate", ctx, id, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// SummaryUpdate indicates an expected call of SummaryUpdate.
func (mr *MockDBHandlerMockRecorder) SummaryUpdate(ctx, id, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SummaryUpdate", reflect.TypeOf((*MockDBHandler)(nil).SummaryUpdate), ctx, id, fields)
}
