CREATE TABLE ps_endpoints (
  id            varchar(40) NOT NULL,
  transport     varchar(40) DEFAULT NULL,
  aors          varchar(200) DEFAULT NULL,
  auth          varchar(40) DEFAULT NULL,
  context       varchar(40) DEFAULT NULL,

  identify_by varchar(80) DEFAULT NULL,
  from_domain varchar(40) DEFAULT NULL,

--   disallow varchar(200) DEFAULT NULL,
--   allow varchar(200) DEFAULT NULL,

--   direct_media enum('yes','no') DEFAULT NULL,
--   connected_line_method enum('invite','reinvite','update') DEFAULT NULL,
--   direct_media_method enum('invite','reinvite','update') DEFAULT NULL,
--   direct_media_glare_mitigation enum('none','outgoing','incoming') DEFAULT NULL,
--   disable_direct_media_on_nat enum('yes','no') DEFAULT NULL,
--   dtmf_mode enum('rfc4733','inband','info','auto','auto_info') DEFAULT NULL,
--   external_media_address varchar(40) DEFAULT NULL,
--   force_rport enum('yes','no') DEFAULT NULL,
--   ice_support enum('yes','no') DEFAULT NULL,
--   identify_by varchar(80) DEFAULT NULL,
--   mailboxes varchar(40) DEFAULT NULL,
--   moh_suggest varchar(40) DEFAULT NULL,
--   outbound_auth varchar(40) DEFAULT NULL,
--   outbound_proxy varchar(40) DEFAULT NULL,
--   rewrite_contact enum('yes','no') DEFAULT NULL,

--   rtp_ipv6 enum('yes','no') DEFAULT NULL,
--   rtp_symmetric enum('yes','no') DEFAULT NULL,

--   send_diversion enum('yes','no') DEFAULT NULL,
--   send_pai enum('yes','no') DEFAULT NULL,
--   send_rpid enum('yes','no') DEFAULT NULL,
--   timers_min_se int(11) DEFAULT NULL,
--   timers enum('forced','no','required','yes') DEFAULT NULL,
--   timers_sess_expires int(11) DEFAULT NULL,

--   callerid varchar(40) DEFAULT NULL,
--   callerid_privacy enum('allowed_not_screened','allowed_passed_screened','allowed_failed_screened','allowed','prohib_not_screened','prohib_passed_screened','prohib_failed_screened','prohib','unavailable') DEFAULT NULL,
--   callerid_tag varchar(40) DEFAULT NULL,

--   100rel enum('no','required','yes') DEFAULT NULL,
--   aggregate_mwi enum('yes','no') DEFAULT NULL,

--   trust_id_inbound enum('yes','no') DEFAULT NULL,
--   trust_id_outbound enum('yes','no') DEFAULT NULL,

--   use_ptime enum('yes','no') DEFAULT NULL,
--   use_avpf enum('yes','no') DEFAULT NULL,

--   media_encryption enum('no','sdes','dtls') DEFAULT NULL,
--   inband_progress enum('yes','no') DEFAULT NULL,
--   call_group varchar(40) DEFAULT NULL,
--   pickup_group varchar(40) DEFAULT NULL,
--   named_call_group varchar(40) DEFAULT NULL,
--   named_pickup_group varchar(40) DEFAULT NULL,
--   device_state_busy_at int(11) DEFAULT NULL,

--   fax_detect enum('yes','no') DEFAULT NULL,
--   t38_udptl enum('yes','no') DEFAULT NULL,
--   t38_udptl_ec enum('none','fec','redundancy') DEFAULT NULL,
--   t38_udptl_maxdatagram int(11) DEFAULT NULL,
--   t38_udptl_nat enum('yes','no') DEFAULT NULL,
--   t38_udptl_ipv6 enum('yes','no') DEFAULT NULL,
--   tone_zone varchar(40) DEFAULT NULL,

--   language varchar(40) DEFAULT NULL,
--   one_touch_recording enum('yes','no') DEFAULT NULL,
--   record_on_feature varchar(40) DEFAULT NULL,
--   record_off_feature varchar(40) DEFAULT NULL,
--   rtp_engine varchar(40) DEFAULT NULL,
--   allow_transfer enum('yes','no') DEFAULT NULL,
--   allow_subscribe enum('yes','no') DEFAULT NULL,

--   sdp_owner varchar(40) DEFAULT NULL,
--   sdp_session varchar(40) DEFAULT NULL,

--   tos_audio varchar(10) DEFAULT NULL,
--   tos_video varchar(10) DEFAULT NULL,
--   sub_min_expiry int(11) DEFAULT NULL,

--   from_user varchar(40) DEFAULT NULL,
--   mwi_from_user varchar(40) DEFAULT NULL,

--   dtls_verify varchar(40) DEFAULT NULL,
--   dtls_rekey varchar(40) DEFAULT NULL,
--   dtls_cert_file varchar(200) DEFAULT NULL,
--   dtls_private_key varchar(200) DEFAULT NULL,
--   dtls_cipher varchar(200) DEFAULT NULL,
--   dtls_ca_file varchar(200) DEFAULT NULL,
--   dtls_ca_path varchar(200) DEFAULT NULL,
--   dtls_setup enum('active','passive','actpass') DEFAULT NULL,

--   srtp_tag_32 enum('yes','no') DEFAULT NULL,
--   media_address varchar(40) DEFAULT NULL,
--   redirect_method enum('user','uri_core','uri_pjsip') DEFAULT NULL,
--   set_var text,
--   cos_audio int(11) DEFAULT NULL,
--   cos_video int(11) DEFAULT NULL,
--   message_context varchar(40) DEFAULT NULL,
--   force_avp enum('yes','no') DEFAULT NULL,
--   media_use_received_transport enum('yes','no') DEFAULT NULL,
--   accountcode varchar(80) DEFAULT NULL,
--   user_eq_phone enum('yes','no') DEFAULT NULL,
--   moh_passthrough enum('yes','no') DEFAULT NULL,
--   media_encryption_optimistic enum('yes','no') DEFAULT NULL,
--   rpid_immediate enum('yes','no') DEFAULT NULL,
--   g726_non_standard enum('yes','no') DEFAULT NULL,

--   rtp_keepalive int(11) DEFAULT NULL,
--   rtp_timeout int(11) DEFAULT NULL,
--   rtp_timeout_hold int(11) DEFAULT NULL,
--   bind_rtp_to_media_address enum('yes','no') DEFAULT NULL,
--   voicemail_extension varchar(40) DEFAULT NULL,
--   mwi_subscribe_replaces_unsolicited enum('0','1','off','on','false','true','no','yes') DEFAULT NULL,

--   deny varchar(95) DEFAULT NULL,
--   permit varchar(95) DEFAULT NULL,
--   acl varchar(40) DEFAULT NULL,
--   contact_deny varchar(95) DEFAULT NULL,
--   contact_permit varchar(95) DEFAULT NULL,
--   contact_acl varchar(40) DEFAULT NULL,
--   subscribe_context varchar(40) DEFAULT NULL,
--   fax_detect_timeout int(11) DEFAULT NULL,
--   contact_user varchar(80) DEFAULT NULL,
--   preferred_codec_only enum('yes','no') DEFAULT NULL,
--   asymmetric_rtp_codec enum('yes','no') DEFAULT NULL,
--   rtcp_mux enum('yes','no') DEFAULT NULL,

--   allow_overlap enum('yes','no') DEFAULT NULL,
--   refer_blind_progress enum('yes','no') DEFAULT NULL,
--   notify_early_inuse_ringing enum('yes','no') DEFAULT NULL,
--   max_audio_streams int(11) DEFAULT NULL,
--   max_video_streams int(11) DEFAULT NULL,
--   webrtc enum('yes','no') DEFAULT NULL,
--   dtls_fingerprint enum('SHA-1','SHA-256') DEFAULT NULL,
--   incoming_mwi_mailbox varchar(40) DEFAULT NULL,
--   bundle enum('yes','no') DEFAULT NULL,
--   dtls_auto_generate_cert enum('yes','no') DEFAULT NULL,
--   follow_early_media_fork enum('yes','no') DEFAULT NULL,
--   accept_multiple_sdp_answers enum('yes','no') DEFAULT NULL,
--   suppress_q850_reason_headers enum('yes','no') DEFAULT NULL,
--   trust_connected_line enum('0','1','off','on','false','true','no','yes') DEFAULT NULL,
--   send_connected_line enum('0','1','off','on','false','true','no','yes') DEFAULT NULL,
--   ignore_183_without_sdp enum('0','1','off','on','false','true','no','yes') DEFAULT NULL,

--   codec_prefs_incoming_offer varchar(128) DEFAULT NULL,
--   codec_prefs_outgoing_offer varchar(128) DEFAULT NULL,
--   codec_prefs_incoming_answer varchar(128) DEFAULT NULL,
--   codec_prefs_outgoing_answer varchar(128) DEFAULT NULL,
--   stir_shaken enum('0','1','off','on','false','true','no','yes') DEFAULT NULL,
--   send_history_info enum('0','1','off','on','false','true','no','yes') DEFAULT NULL,

  primary key(id)
)


