// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -package messagechathandler -destination ./mock_main.go -source main.go -build_flags=-mod=mod
//

// Package messagechathandler is a generated GoMock package.
package messagechathandler

import (
	context "context"
	media "monorepo/bin-chat-manager/models/media"
	messagechat "monorepo/bin-chat-manager/models/messagechat"
	address "monorepo/bin-common-handler/models/address"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMessagechatHandler is a mock of MessagechatHandler interface.
type MockMessagechatHandler struct {
	ctrl     *gomock.Controller
	recorder *MockMessagechatHandlerMockRecorder
	isgomock struct{}
}

// MockMessagechatHandlerMockRecorder is the mock recorder for MockMessagechatHandler.
type MockMessagechatHandlerMockRecorder struct {
	mock *MockMessagechatHandler
}

// NewMockMessagechatHandler creates a new mock instance.
func NewMockMessagechatHandler(ctrl *gomock.Controller) *MockMessagechatHandler {
	mock := &MockMessagechatHandler{ctrl: ctrl}
	mock.recorder = &MockMessagechatHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessagechatHandler) EXPECT() *MockMessagechatHandlerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMessagechatHandler) Create(ctx context.Context, customerID, chatID uuid.UUID, source *address.Address, messageType messagechat.Type, text string, medias []media.Media) (*messagechat.Messagechat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, customerID, chatID, source, messageType, text, medias)
	ret0, _ := ret[0].(*messagechat.Messagechat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMessagechatHandlerMockRecorder) Create(ctx, customerID, chatID, source, messageType, text, medias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMessagechatHandler)(nil).Create), ctx, customerID, chatID, source, messageType, text, medias)
}

// Delete mocks base method.
func (m *MockMessagechatHandler) Delete(ctx context.Context, id uuid.UUID) (*messagechat.Messagechat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*messagechat.Messagechat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockMessagechatHandlerMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMessagechatHandler)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockMessagechatHandler) Get(ctx context.Context, id uuid.UUID) (*messagechat.Messagechat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*messagechat.Messagechat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMessagechatHandlerMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMessagechatHandler)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockMessagechatHandler) List(ctx context.Context, token string, limit uint64, filters map[messagechat.Field]any) ([]*messagechat.Messagechat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, token, limit, filters)
	ret0, _ := ret[0].([]*messagechat.Messagechat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMessagechatHandlerMockRecorder) List(ctx, token, limit, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMessagechatHandler)(nil).List), ctx, token, limit, filters)
}
