// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -package servicehandler -destination ./mock_servicehandler.go -source main.go -build_flags=-mod=mod
//

// Package servicehandler is a generated GoMock package.
package servicehandler

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServiceHandler is a mock of ServiceHandler interface.
type MockServiceHandler struct {
	ctrl     *gomock.Controller
	recorder *MockServiceHandlerMockRecorder
	isgomock struct{}
}

// MockServiceHandlerMockRecorder is the mock recorder for MockServiceHandler.
type MockServiceHandlerMockRecorder struct {
	mock *MockServiceHandler
}

// NewMockServiceHandler creates a new mock instance.
func NewMockServiceHandler(ctrl *gomock.Controller) *MockServiceHandler {
	mock := &MockServiceHandler{ctrl: ctrl}
	mock.recorder = &MockServiceHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceHandler) EXPECT() *MockServiceHandlerMockRecorder {
	return m.recorder
}

// Billing mocks base method.
func (m *MockServiceHandler) Billing(ctx context.Context, r *http.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Billing", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Billing indicates an expected call of Billing.
func (mr *MockServiceHandlerMockRecorder) Billing(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Billing", reflect.TypeOf((*MockServiceHandler)(nil).Billing), ctx, r)
}

// Conversation mocks base method.
func (m *MockServiceHandler) Conversation(ctx context.Context, r *http.Request) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Conversation", ctx, r)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Conversation indicates an expected call of Conversation.
func (mr *MockServiceHandlerMockRecorder) Conversation(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Conversation", reflect.TypeOf((*MockServiceHandler)(nil).Conversation), ctx, r)
}

// Email mocks base method.
func (m *MockServiceHandler) Email(ctx context.Context, r *http.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Email", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Email indicates an expected call of Email.
func (mr *MockServiceHandlerMockRecorder) Email(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Email", reflect.TypeOf((*MockServiceHandler)(nil).Email), ctx, r)
}

// Message mocks base method.
func (m *MockServiceHandler) Message(ctx context.Context, r *http.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Message", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Message indicates an expected call of Message.
func (mr *MockServiceHandlerMockRecorder) Message(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Message", reflect.TypeOf((*MockServiceHandler)(nil).Message), ctx, r)
}
