apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bin-manager

resources:
  - namespace.yml
  - secret.yml
  - deployment.yml
  - service.yml

images:
- name: conference-manager-image
  newName: conference-manager
  newTag: latest

