apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-manager
  namespace: bin-manager
  labels:
    app: sentinel-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentinel-manager
  template:
    metadata:
      namespace: bin-manager
      labels:
        app: sentinel-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "2112"
    spec:
      containers:
        - name: sentinel-manager
          image: sentinel-manager-image
          command:
            - './sentinel-manager'
          env:
            - name: PROMETHEUS_ENDPOINT
              value: "/metrics"
            - name: PROMETHEUS_LISTEN_ADDRESS
              value: ":2112"
            - name: RABBITMQ_ADDRESS
              value: ${RABBITMQ_ADDRESS}
          ports:
            - name: metrics
              protocol: "TCP"
              containerPort: 2112
            - name: grpc
              protocol: "TCP"
              containerPort: 80
          resources:
            limits:
              cpu: "30m"
              memory: "20Mi"
