apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: voip
subjects:
  - kind: ServiceAccount
    name: default
    namespace: bin-manager
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
