---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-manager
  namespace: bin-manager

spec:
  type: ClusterIP
  selector:
    app: sentinel-manager
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
