// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -package customerhandler -destination ./mock_main.go -source main.go -build_flags=-mod=mod
//

// Package customerhandler is a generated GoMock package.
package customerhandler

import (
	context "context"
	customer "monorepo/bin-customer-manager/models/customer"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCustomerHandler is a mock of CustomerHandler interface.
type MockCustomerHandler struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerHandlerMockRecorder
	isgomock struct{}
}

// MockCustomerHandlerMockRecorder is the mock recorder for MockCustomerHandler.
type MockCustomerHandlerMockRecorder struct {
	mock *MockCustomerHandler
}

// NewMockCustomerHandler creates a new mock instance.
func NewMockCustomerHandler(ctrl *gomock.Controller) *MockCustomerHandler {
	mock := &MockCustomerHandler{ctrl: ctrl}
	mock.recorder = &MockCustomerHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerHandler) EXPECT() *MockCustomerHandlerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCustomerHandler) Create(ctx context.Context, name, detail, email, phoneNumber, address string, webhookMethod customer.WebhookMethod, webhookURI string) (*customer.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name, detail, email, phoneNumber, address, webhookMethod, webhookURI)
	ret0, _ := ret[0].(*customer.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCustomerHandlerMockRecorder) Create(ctx, name, detail, email, phoneNumber, address, webhookMethod, webhookURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCustomerHandler)(nil).Create), ctx, name, detail, email, phoneNumber, address, webhookMethod, webhookURI)
}

// Delete mocks base method.
func (m *MockCustomerHandler) Delete(ctx context.Context, id uuid.UUID) (*customer.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*customer.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockCustomerHandlerMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCustomerHandler)(nil).Delete), ctx, id)
}

// EmailVerify mocks base method.
func (m *MockCustomerHandler) EmailVerify(ctx context.Context, token string) (*customer.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmailVerify", ctx, token)
	ret0, _ := ret[0].(*customer.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmailVerify indicates an expected call of EmailVerify.
func (mr *MockCustomerHandlerMockRecorder) EmailVerify(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmailVerify", reflect.TypeOf((*MockCustomerHandler)(nil).EmailVerify), ctx, token)
}

// Get mocks base method.
func (m *MockCustomerHandler) Get(ctx context.Context, id uuid.UUID) (*customer.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*customer.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCustomerHandlerMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCustomerHandler)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockCustomerHandler) List(ctx context.Context, size uint64, token string, filters map[customer.Field]any) ([]*customer.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, size, token, filters)
	ret0, _ := ret[0].([]*customer.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCustomerHandlerMockRecorder) List(ctx, size, token, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCustomerHandler)(nil).List), ctx, size, token, filters)
}

// RunCleanupUnverified mocks base method.
func (m *MockCustomerHandler) RunCleanupUnverified(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RunCleanupUnverified", ctx)
}

// RunCleanupUnverified indicates an expected call of RunCleanupUnverified.
func (mr *MockCustomerHandlerMockRecorder) RunCleanupUnverified(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunCleanupUnverified", reflect.TypeOf((*MockCustomerHandler)(nil).RunCleanupUnverified), ctx)
}

// Signup mocks base method.
func (m *MockCustomerHandler) Signup(ctx context.Context, name, detail, email, phoneNumber, address string, webhookMethod customer.WebhookMethod, webhookURI string) (*customer.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signup", ctx, name, detail, email, phoneNumber, address, webhookMethod, webhookURI)
	ret0, _ := ret[0].(*customer.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signup indicates an expected call of Signup.
func (mr *MockCustomerHandlerMockRecorder) Signup(ctx, name, detail, email, phoneNumber, address, webhookMethod, webhookURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signup", reflect.TypeOf((*MockCustomerHandler)(nil).Signup), ctx, name, detail, email, phoneNumber, address, webhookMethod, webhookURI)
}

// UpdateBasicInfo mocks base method.
func (m *MockCustomerHandler) UpdateBasicInfo(ctx context.Context, id uuid.UUID, name, detail, email, phoneNumber, address string, webhookMethod customer.WebhookMethod, webhookURI string) (*customer.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBasicInfo", ctx, id, name, detail, email, phoneNumber, address, webhookMethod, webhookURI)
	ret0, _ := ret[0].(*customer.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBasicInfo indicates an expected call of UpdateBasicInfo.
func (mr *MockCustomerHandlerMockRecorder) UpdateBasicInfo(ctx, id, name, detail, email, phoneNumber, address, webhookMethod, webhookURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBasicInfo", reflect.TypeOf((*MockCustomerHandler)(nil).UpdateBasicInfo), ctx, id, name, detail, email, phoneNumber, address, webhookMethod, webhookURI)
}

// UpdateBillingAccountID mocks base method.
func (m *MockCustomerHandler) UpdateBillingAccountID(ctx context.Context, id, billingAccountID uuid.UUID) (*customer.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBillingAccountID", ctx, id, billingAccountID)
	ret0, _ := ret[0].(*customer.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBillingAccountID indicates an expected call of UpdateBillingAccountID.
func (mr *MockCustomerHandlerMockRecorder) UpdateBillingAccountID(ctx, id, billingAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBillingAccountID", reflect.TypeOf((*MockCustomerHandler)(nil).UpdateBillingAccountID), ctx, id, billingAccountID)
}
