// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -package participanthandler -destination ./mock_main.go -source main.go -build_flags=-mod=mod
//

// Package participanthandler is a generated GoMock package.
package participanthandler

import (
	context "context"
	participant "monorepo/bin-ai-manager/models/participant"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockParticipantHandler is a mock of ParticipantHandler interface.
type MockParticipantHandler struct {
	ctrl     *gomock.Controller
	recorder *MockParticipantHandlerMockRecorder
	isgomock struct{}
}

// MockParticipantHandlerMockRecorder is the mock recorder for MockParticipantHandler.
type MockParticipantHandlerMockRecorder struct {
	mock *MockParticipantHandler
}

// NewMockParticipantHandler creates a new mock instance.
func NewMockParticipantHandler(ctrl *gomock.Controller) *MockParticipantHandler {
	mock := &MockParticipantHandler{ctrl: ctrl}
	mock.recorder = &MockParticipantHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParticipantHandler) EXPECT() *MockParticipantHandlerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockParticipantHandler) Create(ctx context.Context, aicallID, aiID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, aicallID, aiID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockParticipantHandlerMockRecorder) Create(ctx, aicallID, aiID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockParticipantHandler)(nil).Create), ctx, aicallID, aiID)
}

// ListByAIID mocks base method.
func (m *MockParticipantHandler) ListByAIID(ctx context.Context, aiID uuid.UUID, size uint64, token string) ([]*participant.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAIID", ctx, aiID, size, token)
	ret0, _ := ret[0].([]*participant.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAIID indicates an expected call of ListByAIID.
func (mr *MockParticipantHandlerMockRecorder) ListByAIID(ctx, aiID, size, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAIID", reflect.TypeOf((*MockParticipantHandler)(nil).ListByAIID), ctx, aiID, size, token)
}

// ListByAIcallID mocks base method.
func (m *MockParticipantHandler) ListByAIcallID(ctx context.Context, aicallID uuid.UUID, size uint64, token string) ([]*participant.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAIcallID", ctx, aicallID, size, token)
	ret0, _ := ret[0].([]*participant.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAIcallID indicates an expected call of ListByAIcallID.
func (mr *MockParticipantHandlerMockRecorder) ListByAIcallID(ctx, aicallID, size, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAIcallID", reflect.TypeOf((*MockParticipantHandler)(nil).ListByAIcallID), ctx, aicallID, size, token)
}
