apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-manager
  labels:
    app: api-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-manager
  template:
    metadata:
      labels:
        app: api-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "2112"
    spec:
      containers:
        - name: api-manager
          image: api-manager-image
          command:
            - './api-manager'
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: bin-manager-secrets
                  key: DATABASE_DSN_BIN
            - name: PROMETHEUS_ENDPOINT
              value: "/metrics"
            - name: PROMETHEUS_LISTEN_ADDRESS
              value: ":2112"
            - name: RABBITMQ_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: bin-manager-secrets
                  key: RABBITMQ_ADDRESS
            - name: REDIS_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: bin-manager-secrets
                  key: REDIS_ADDRESS
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bin-manager-secrets
                  key: REDIS_PASSWORD
            - name: REDIS_DATABASE
              valueFrom:
                secretKeyRef:
                  name: bin-manager-secrets
                  key: REDIS_DATABASE
            - name: SSL_PRIVKEY_BASE64
              valueFrom:
                secretKeyRef:
                  name: bin-manager-secrets
                  key: SSL_PRIVKEY_API_BASE64
            - name: SSL_CERT_BASE64
              valueFrom:
                secretKeyRef:
                  name: bin-manager-secrets
                  key: SSL_CERT_API_BASE64
            - name: GCP_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: bin-manager-secrets
                  key: GCP_PROJECT_ID
            - name: GCP_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: bin-manager-secrets
                  key: GCP_BUCKET_NAME_TMP
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: bin-manager-secrets
                  key: JWT_KEY
          readinessProbe:
            httpGet:
              path: /ping
              port: 443
              scheme: HTTPS
          resources:
            requests:
              cpu: "20m"
              memory: "10Mi"
            limits:
              cpu: "200m"
              memory: "100Mi"
          ports:
            - containerPort: 2112
              name: metrics
              protocol: TCP
            - containerPort: 443
              name: service
              protocol: TCP
            - containerPort: 9000
              name: audiosocket
              protocol: TCP
