apiVersion: v1
kind: Service
metadata:
  name: api-manager
  # annotations:
  #   cloud.google.com/load-balancer-type: "Internal"
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "api-manager-static-ip"

spec:
  type: LoadBalancer
  selector:
    app: api-manager
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
