// Code generated by MockGen. DO NOT EDIT.
// Source: main.go

// Package bridgehandler is a generated GoMock package.
package bridgehandler

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/gofrs/uuid"
	gomock "github.com/golang/mock/gomock"
	bridge "gitlab.com/voipbin/bin-manager/call-manager.git/models/bridge"
)

// MockBridgeHandler is a mock of BridgeHandler interface.
type MockBridgeHandler struct {
	ctrl     *gomock.Controller
	recorder *MockBridgeHandlerMockRecorder
}

// MockBridgeHandlerMockRecorder is the mock recorder for MockBridgeHandler.
type MockBridgeHandlerMockRecorder struct {
	mock *MockBridgeHandler
}

// NewMockBridgeHandler creates a new mock instance.
func NewMockBridgeHandler(ctrl *gomock.Controller) *MockBridgeHandler {
	mock := &MockBridgeHandler{ctrl: ctrl}
	mock.recorder = &MockBridgeHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBridgeHandler) EXPECT() *MockBridgeHandlerMockRecorder {
	return m.recorder
}

// AddChannelID mocks base method.
func (m *MockBridgeHandler) AddChannelID(ctx context.Context, id, channelID string) (*bridge.Bridge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChannelID", ctx, id, channelID)
	ret0, _ := ret[0].(*bridge.Bridge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddChannelID indicates an expected call of AddChannelID.
func (mr *MockBridgeHandlerMockRecorder) AddChannelID(ctx, id, channelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChannelID", reflect.TypeOf((*MockBridgeHandler)(nil).AddChannelID), ctx, id, channelID)
}

// Create mocks base method.
func (m *MockBridgeHandler) Create(ctx context.Context, asteriskID, id, name string, bridgeType bridge.Type, tech bridge.Tech, class, creator, videoMode, videoSourceID string, channelIDs []string, referenceType bridge.ReferenceType, referenceID uuid.UUID) (*bridge.Bridge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, asteriskID, id, name, bridgeType, tech, class, creator, videoMode, videoSourceID, channelIDs, referenceType, referenceID)
	ret0, _ := ret[0].(*bridge.Bridge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBridgeHandlerMockRecorder) Create(ctx, asteriskID, id, name, bridgeType, tech, class, creator, videoMode, videoSourceID, channelIDs, referenceType, referenceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBridgeHandler)(nil).Create), ctx, asteriskID, id, name, bridgeType, tech, class, creator, videoMode, videoSourceID, channelIDs, referenceType, referenceID)
}

// Delete mocks base method.
func (m *MockBridgeHandler) Delete(ctx context.Context, id string) (*bridge.Bridge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*bridge.Bridge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockBridgeHandlerMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBridgeHandler)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockBridgeHandler) Get(ctx context.Context, id string) (*bridge.Bridge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*bridge.Bridge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBridgeHandlerMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBridgeHandler)(nil).Get), ctx, id)
}

// GetWithTimeout mocks base method.
func (m *MockBridgeHandler) GetWithTimeout(ctx context.Context, id string, timeout time.Duration) (*bridge.Bridge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithTimeout", ctx, id, timeout)
	ret0, _ := ret[0].(*bridge.Bridge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithTimeout indicates an expected call of GetWithTimeout.
func (mr *MockBridgeHandlerMockRecorder) GetWithTimeout(ctx, id, timeout interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithTimeout", reflect.TypeOf((*MockBridgeHandler)(nil).GetWithTimeout), ctx, id, timeout)
}

// RemoveChannelID mocks base method.
func (m *MockBridgeHandler) RemoveChannelID(ctx context.Context, id, channelID string) (*bridge.Bridge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveChannelID", ctx, id, channelID)
	ret0, _ := ret[0].(*bridge.Bridge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveChannelID indicates an expected call of RemoveChannelID.
func (mr *MockBridgeHandlerMockRecorder) RemoveChannelID(ctx, id, channelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveChannelID", reflect.TypeOf((*MockBridgeHandler)(nil).RemoveChannelID), ctx, id, channelID)
}
