// Code generated by MockGen. DO NOT EDIT.
// Source: main.go

// Package sttgoogle is a generated GoMock package.
package sttgoogle

import (
	context "context"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	gomock "github.com/golang/mock/gomock"
	common "gitlab.com/voipbin/bin-manager/transcribe-manager.git/models/common"
	streaming "gitlab.com/voipbin/bin-manager/transcribe-manager.git/models/streaming"
	transcribe "gitlab.com/voipbin/bin-manager/transcribe-manager.git/models/transcribe"
	transcript "gitlab.com/voipbin/bin-manager/transcribe-manager.git/models/transcript"
)

// MockSTTGoogle is a mock of STTGoogle interface.
type MockSTTGoogle struct {
	ctrl     *gomock.Controller
	recorder *MockSTTGoogleMockRecorder
}

// MockSTTGoogleMockRecorder is the mock recorder for MockSTTGoogle.
type MockSTTGoogleMockRecorder struct {
	mock *MockSTTGoogle
}

// NewMockSTTGoogle creates a new mock instance.
func NewMockSTTGoogle(ctrl *gomock.Controller) *MockSTTGoogle {
	mock := &MockSTTGoogle{ctrl: ctrl}
	mock.recorder = &MockSTTGoogleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSTTGoogle) EXPECT() *MockSTTGoogleMockRecorder {
	return m.recorder
}

// Recording mocks base method.
func (m *MockSTTGoogle) Recording(ctx context.Context, recordingID uuid.UUID, language string) (*transcript.Transcript, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recording", ctx, recordingID, language)
	ret0, _ := ret[0].(*transcript.Transcript)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recording indicates an expected call of Recording.
func (mr *MockSTTGoogleMockRecorder) Recording(ctx, recordingID, language interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recording", reflect.TypeOf((*MockSTTGoogle)(nil).Recording), ctx, recordingID, language)
}

// Start mocks base method.
func (m *MockSTTGoogle) Start(ctx context.Context, tr *transcribe.Transcribe, direction common.Direction) (*streaming.Streaming, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, tr, direction)
	ret0, _ := ret[0].(*streaming.Streaming)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockSTTGoogleMockRecorder) Start(ctx, tr, direction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSTTGoogle)(nil).Start), ctx, tr, direction)
}

// Stop mocks base method.
func (m *MockSTTGoogle) Stop(ctx context.Context, st *streaming.Streaming) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, st)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockSTTGoogleMockRecorder) Stop(ctx, st interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockSTTGoogle)(nil).Stop), ctx, st)
}
