apiVersion: apps/v1
kind: Deployment
metadata:
  name: campaign-manager
  labels:
    app: campaign-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: campaign-manager
  template:
    metadata:
      labels:
        app: campaign-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "2112"
    spec:
      containers:
        - name: campaign-manager
          image: campaign-manager-image
          command:
            - './campaign-manager'
          env:
            - name: DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: bin-manager-secrets
                  key: DATABASE_DSN
            - name: PROMETHEUS_ENDPOINT
              value: "/metrics"
            - name: PROMETHEUS_LISTEN_ADDRESS
              value: ":2112"
            - name: RABBITMQ_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: bin-manager-secrets
                  key: RABBITMQ_ADDRESS
            - name: REDIS_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: bin-manager-secrets
                  key: REDIS_ADDRESS
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bin-manager-secrets
                  key: REDIS_PASSWORD
            - name: REDIS_DATABASE
              valueFrom:
                secretKeyRef:
                  name: bin-manager-secrets
                  key: REDIS_DATABASE
            - name: CLICKHOUSE_ADDRESS
              value: "clickhouse.infrastructure.svc.cluster.local:9000"
          ports:
            - name: metrics
              protocol: "TCP"
              containerPort: 2112
          resources:
            requests:
              cpu: "1m"
              memory: "3M"
            limits:
              cpu: "5m"
              memory: "30M"
