// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -package chatgpthandler -destination ./mock_main.go -source main.go -build_flags=-mod=mod
//

// Package chatgpthandler is a generated GoMock package.
package chatgpthandler

import (
	context "context"
	chatbotcall "monorepo/bin-chatbot-manager/models/chatbotcall"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockChatgptHandler is a mock of ChatgptHandler interface.
type MockChatgptHandler struct {
	ctrl     *gomock.Controller
	recorder *MockChatgptHandlerMockRecorder
	isgomock struct{}
}

// MockChatgptHandlerMockRecorder is the mock recorder for MockChatgptHandler.
type MockChatgptHandlerMockRecorder struct {
	mock *MockChatgptHandler
}

// NewMockChatgptHandler creates a new mock instance.
func NewMockChatgptHandler(ctrl *gomock.Controller) *MockChatgptHandler {
	mock := &MockChatgptHandler{ctrl: ctrl}
	mock.recorder = &MockChatgptHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatgptHandler) EXPECT() *MockChatgptHandlerMockRecorder {
	return m.recorder
}

// ChatMessage mocks base method.
func (m *MockChatgptHandler) ChatMessage(ctx context.Context, cc *chatbotcall.Chatbotcall, text string) ([]chatbotcall.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatMessage", ctx, cc, text)
	ret0, _ := ret[0].([]chatbotcall.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatMessage indicates an expected call of ChatMessage.
func (mr *MockChatgptHandlerMockRecorder) ChatMessage(ctx, cc, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatMessage", reflect.TypeOf((*MockChatgptHandler)(nil).ChatMessage), ctx, cc, text)
}

// ChatNew mocks base method.
func (m *MockChatgptHandler) ChatNew(ctx context.Context, cc *chatbotcall.Chatbotcall, initPrompt string) ([]chatbotcall.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatNew", ctx, cc, initPrompt)
	ret0, _ := ret[0].([]chatbotcall.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatNew indicates an expected call of ChatNew.
func (mr *MockChatgptHandlerMockRecorder) ChatNew(ctx, cc, initPrompt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatNew", reflect.TypeOf((*MockChatgptHandler)(nil).ChatNew), ctx, cc, initPrompt)
}
